/*
<FluidEQ: System-wide parametric audio equalizer interface>
Copyright (C) <2026>  <Ivan Carmenates Garcia>
SPDX-License-Identifier: GPL-3.0-or-later
*/

/**
 * `resolve_chain` and its grammar, held to the same config layout
 * `apoConfigReader.ts` reads: includes, `Device:` guards, and the five
 * commands FluidEQ writes. The file system here is a `std::map`, not disk —
 * this library never touches a Windows API, so the test does not need to
 * either.
 */

#include "fluideq_engine/config.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <map>
#include <string>

using fluideq_engine::Band;
using fluideq_engine::Chain;
using fluideq_engine::Endpoint;
using fluideq_engine::FileProvider;
using fluideq_engine::FilterType;
using fluideq_engine::GraphicPoint;
using fluideq_engine::Line;
using fluideq_engine::device_matches;
using fluideq_engine::parse_filter;
using fluideq_engine::parse_graphic;
using fluideq_engine::resolve_chain;
using fluideq_engine::tokenize;

namespace {

int g_failures = 0;

void check_impl(bool ok, const char* expr, const char* file, int line) {
  if (!ok) {
    std::printf("  FAIL %s:%d: %s\n", file, line, expr);
    ++g_failures;
  }
}

// Variadic rather than single-argument: the preprocessor splits macro
// arguments on every top-level comma, including one inside a brace-init-list
// like `std::vector<std::string>{"Copy", "Delay"}` below, which is not
// wrapped in its own parentheses at the call site. `__VA_ARGS__` re-joins
// those pieces with their original commas intact, and `(__VA_ARGS__)`
// restores the single expression the call site meant.
#define CHECK(...) check_impl((__VA_ARGS__), #__VA_ARGS__, __FILE__, __LINE__)

// The provider a real caller would back with `ReadFile`. Here it is a fixed
// map, so a test can assert exactly which paths the resolver opened and in
// what order, and can arrange for a path to be absent to exercise the
// "unreadable" branch of `FileProvider` on purpose.
using Files = std::map<std::wstring, std::string>;

FileProvider provider(const Files& files) {
  return [&files](const std::wstring& path) -> std::optional<std::string> {
    const auto found = files.find(path);
    if (found == files.end()) {
      return std::nullopt;
    }
    return found->second;
  };
}

void follows_includes_and_device_guards() {
  std::printf("follows includes and device guards\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: fluideq.txt\r\n";
  files[L"C:\\cfg\\fluideq.txt"] =
      "# Generated by FluidEQ.\r\n"
      "Device: all\r\nChannel: all\r\n"
      "Device: {AAAA}\r\nChannel: all\r\nInclude: fluideq-device-a.txt\r\n"
      "Device: {BBBB}\r\nChannel: all\r\nInclude: fluideq-device-b.txt\r\n";
  files[L"C:\\cfg\\fluideq-device-a.txt"] =
      "Convolution: fluideq-convolution-a.wav\r\n"
      "Include: fluideq-a-eq.txt\r\nPreamp: -3.5 dB\r\nInclude: fluideq-a-custom.txt\r\n";
  files[L"C:\\cfg\\fluideq-a-eq.txt"] =
      "Filter 1: ON PK Fc 1000 Hz Gain -3 dB Q 1.41\r\nFilter 2: ON HPQ Fc 30 Hz Q 0.71\r\n";
  files[L"C:\\cfg\\fluideq-a-custom.txt"] = "Copy: L=R\r\nDelay: 10 ms\r\n";
  files[L"C:\\cfg\\fluideq-device-b.txt"] = "Filter 1: ON PK Fc 500 Hz Gain 9 dB Q 1\r\n";
  const auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers (Realtek)"}, provider(files));
  CHECK(chain.matched);
  CHECK(chain.bands.size() == 2);
  CHECK(chain.bands[0].frequency == 1000.0);
  CHECK(chain.convolution_path == L"C:\\cfg\\fluideq-convolution-a.wav");
  CHECK(chain.preamp_db == -3.5);
  CHECK(chain.ignored == std::vector<std::string>{"Copy", "Delay"});
  // B's file is never opened while the guard is false.
  CHECK(std::find(chain.files_read.begin(), chain.files_read.end(),
                  L"C:\\cfg\\fluideq-device-b.txt") == chain.files_read.end());
}

void neutral_root_is_passthrough() {
  std::printf("neutral root is passthrough\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: fluideq.txt\r\n";
  files[L"C:\\cfg\\fluideq.txt"] = "# Generated by FluidEQ.\r\n# Neutral.\r\n";
  const auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(!chain.matched);
  CHECK(chain.bands.empty());
}

void missing_root_is_passthrough() {
  std::printf("missing root is passthrough\n");
  const auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider({}));
  CHECK(!chain.matched);
}

/**
 * A missing rack file means "no rack", which is what makes deleting it the
 * cure for a rack that outlived an engine switch: the neutral root cannot
 * silence the rack, because the rack is read before the config tree and
 * outside every `Device:` guard.
 */
void rack_file_absence_means_no_rack() {
  std::printf("rack file absence means no rack\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: fluideq.txt\r\n";
  files[L"C:\\cfg\\fluideq.txt"] = "# Generated by FluidEQ.\r\n# Neutral.\r\n";
  const auto without = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(without.dsp_values.empty());

  files[L"C:\\cfg\\fluideq-dsp.txt"] =
      "# FluidEQ Engine DSP chain v1\r\n1 0.5 -2\r\n";
  const auto with_rack = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(with_rack.dsp_values.size() == 3);
  CHECK(with_rack.dsp_values[1] == 0.5);
  // The neutral root still silences the EQ — only the rack survives it.
  CHECK(!with_rack.matched);
}

void device_pattern_rules() {
  std::printf("device pattern rules\n");
  const Endpoint endpoint{L"{ABCD-1}", L"Speakers (2- Realtek Audio)"};
  CHECK(device_matches("all", endpoint));
  CHECK(device_matches("{abcd-1}", endpoint));
  CHECK(device_matches("Realtek", endpoint));
  CHECK(!device_matches("{FFFF}", endpoint));
  CHECK(!device_matches("Headphones", endpoint));
}

void include_cannot_escape_or_loop() {
  std::printf("include cannot escape or loop\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: ..\\evil.txt\r\nInclude: loop.txt\r\nPreamp: -1\r\n";
  files[L"C:\\evil.txt"] = "Preamp: -40\r\n";
  files[L"C:\\cfg\\loop.txt"] = "Include: loop.txt\r\nFilter 1: ON PK Fc 100 Hz Gain 1 dB Q 1\r\n";
  const auto chain = resolve_chain(L"C:\\cfg", {L"{A}", L"X"}, provider(files));
  CHECK(chain.preamp_db == -1.0);
  CHECK(chain.bands.size() == 1);  // loop.txt read once
}

void include_depth_is_limited() {
  std::printf("include depth is limited\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: d1.txt\r\n";
  for (int n = 1; n <= 9; ++n) {
    const std::wstring path = L"C:\\cfg\\d" + std::to_wstring(n) + L".txt";
    files[path] = "Preamp: -" + std::to_string(n) + "\r\nInclude: d" +
                  std::to_string(n + 1) + ".txt\r\n";
  }
  const auto chain = resolve_chain(L"C:\\cfg", {L"{A}", L"X"}, provider(files));
  // Depth is capped at 8 open frames (root config.txt + 7 Include levels):
  // d7.txt is the 8th and last frame opened, so its "Preamp: -7" is the last
  // one applied, and d7.txt's own "Include: d8.txt" is skipped rather than
  // followed — d8.txt is never opened. See resolve_chain's doc comment.
  CHECK(chain.preamp_db == -7.0);
  CHECK(std::find(chain.files_read.begin(), chain.files_read.end(),
                  L"C:\\cfg\\d7.txt") != chain.files_read.end());
  CHECK(std::find(chain.files_read.begin(), chain.files_read.end(),
                  L"C:\\cfg\\d8.txt") == chain.files_read.end());
}

void filter_grammar() {
  std::printf("filter grammar\n");
  CHECK(parse_filter("ON PK Fc 1000 Hz Gain -3 dB Q 1.41")->quality == 1.41);
  CHECK(parse_filter("ON LS Fc 80 Hz Gain 1 dB Q 0.7")->type == FilterType::LSC);
  CHECK(parse_filter("ON HPQ Fc 30 Hz Q 0.71")->gain_db == 0.0);
  CHECK(!parse_filter("OFF PK Fc 1 Hz Gain 1 dB Q 1"));
  CHECK(!parse_filter("ON XX Fc 100 Hz Gain -3 dB Q 1"));
  CHECK(!parse_filter("ON PK Fc nope Hz Gain -3 dB Q 1"));
  CHECK(!parse_filter("ON PK Fc 100 Hz Gain -3 dB Q 0"));
  const auto bw = parse_filter("ON PK Fc 100 Hz Gain -3 dB BW Oct 1");
  CHECK(bw && std::abs(bw->quality - 1.4142135) < 1e-6);
}

void graphic_and_preamp_grammar() {
  std::printf("graphic and preamp grammar\n");
  const auto points = parse_graphic("20 -2.5; 1000 0; 20000 3");
  CHECK(points.size() == 3 && points[2].gain_db == 3.0);
  CHECK(parse_graphic("20 -2.5; nope").empty());
  const auto lines = tokenize("Preamp: -6\nPreamp:-2.5 dB\n# c\n\nFilter 1: ON PK Fc 1 Hz Gain 1 dB Q 1 # trailing\n");
  CHECK(lines.size() == 3);
  CHECK(lines[0].command == "Preamp" && lines[0].body == "-6");
  CHECK(lines[2].command == "Filter" && lines[2].body == "ON PK Fc 1 Hz Gain 1 dB Q 1");
}

void utf16_with_bom_is_read() {
  std::printf("utf16 with bom is read\n");
  const char16_t text[] = u"\uFEFFPreamp: -1 dB\n";
  const auto lines = tokenize(std::string_view(reinterpret_cast<const char*>(text), sizeof(text) - sizeof(char16_t)));
  CHECK(lines.size() == 1 && lines[0].body == "-1 dB");
}

}  // namespace

int main() {
  std::printf("fluideq engine config\n");
  follows_includes_and_device_guards();
  neutral_root_is_passthrough();
  missing_root_is_passthrough();
  rack_file_absence_means_no_rack();
  device_pattern_rules();
  include_cannot_escape_or_loop();
  include_depth_is_limited();
  filter_grammar();
  graphic_and_preamp_grammar();
  utf16_with_bom_is_read();
  if (g_failures == 0) {
    std::printf("config: ok\n");
    return 0;
  }
  std::printf("\n%d check(s) failed\n", g_failures);
  return 1;
}
