/*
<FluidEQ: System-wide parametric audio equalizer interface>
Copyright (C) <2026>  <Ivan Carmenates Garcia>
SPDX-License-Identifier: GPL-3.0-or-later
*/

/**
 * `resolve_chain` and its grammar, held to the same config layout
 * `apoConfigReader.ts` reads: includes, `Device:` guards, and the five
 * commands FluidEQ writes. The file system here is a `std::map`, not disk —
 * this library never touches a Windows API, so the test does not need to
 * either.
 */

#include "fluideq_engine/config.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <map>
#include <string>

using fluideq_engine::Band;
using fluideq_engine::Chain;
using fluideq_engine::Endpoint;
using fluideq_engine::FileProvider;
using fluideq_engine::FilterType;
using fluideq_engine::GraphicPoint;
using fluideq_engine::Line;
using fluideq_engine::device_matches;
using fluideq_engine::parse_filter;
using fluideq_engine::parse_graphic;
using fluideq_engine::resolve_chain;
using fluideq_engine::tokenize;

namespace {

int g_failures = 0;

void check_impl(bool ok, const char* expr, const char* file, int line) {
  if (!ok) {
    std::printf("  FAIL %s:%d: %s\n", file, line, expr);
    ++g_failures;
  }
}

// Variadic rather than single-argument: the preprocessor splits macro
// arguments on every top-level comma, including one inside a brace-init-list
// like `std::vector<std::string>{"Copy", "Delay"}` below, which is not
// wrapped in its own parentheses at the call site. `__VA_ARGS__` re-joins
// those pieces with their original commas intact, and `(__VA_ARGS__)`
// restores the single expression the call site meant.
#define CHECK(...) check_impl((__VA_ARGS__), #__VA_ARGS__, __FILE__, __LINE__)

// The provider a real caller would back with `ReadFile`. Here it is a fixed
// map, so a test can assert exactly which paths the resolver opened and in
// what order, and can arrange for a path to be absent to exercise the
// "unreadable" branch of `FileProvider` on purpose.
using Files = std::map<std::wstring, std::string>;

FileProvider provider(const Files& files) {
  return [&files](const std::wstring& path) -> std::optional<std::string> {
    const auto found = files.find(path);
    if (found == files.end()) {
      return std::nullopt;
    }
    return found->second;
  };
}

void follows_includes_and_device_guards() {
  std::printf("follows includes and device guards\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: fluideq.txt\r\n";
  files[L"C:\\cfg\\fluideq.txt"] =
      "# Generated by FluidEQ.\r\n"
      "Device: all\r\nChannel: all\r\n"
      "Device: {AAAA}\r\nChannel: all\r\nInclude: fluideq-device-a.txt\r\n"
      "Device: {BBBB}\r\nChannel: all\r\nInclude: fluideq-device-b.txt\r\n";
  files[L"C:\\cfg\\fluideq-device-a.txt"] =
      "Convolution: fluideq-convolution-a.wav\r\n"
      "Include: fluideq-a-eq.txt\r\nPreamp: -3.5 dB\r\nInclude: fluideq-a-custom.txt\r\n";
  files[L"C:\\cfg\\fluideq-a-eq.txt"] =
      "Filter 1: ON PK Fc 1000 Hz Gain -3 dB Q 1.41\r\nFilter 2: ON HPQ Fc 30 Hz Q 0.71\r\n";
  files[L"C:\\cfg\\fluideq-a-custom.txt"] = "Copy: L=R\r\nDelay: 10 ms\r\n";
  files[L"C:\\cfg\\fluideq-device-b.txt"] = "Filter 1: ON PK Fc 500 Hz Gain 9 dB Q 1\r\n";
  const auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers (Realtek)"}, provider(files));
  CHECK(chain.matched);
  CHECK(chain.bands.size() == 2);
  CHECK(chain.bands[0].frequency == 1000.0);
  CHECK(chain.convolution_path == L"C:\\cfg\\fluideq-convolution-a.wav");
  CHECK(chain.preamp_db == -3.5);
  CHECK(chain.ignored == std::vector<std::string>{"Copy", "Delay"});
  // B's file is never opened while the guard is false.
  CHECK(std::find(chain.files_read.begin(), chain.files_read.end(),
                  L"C:\\cfg\\fluideq-device-b.txt") == chain.files_read.end());
}

// The layout FluidEQ writes when a driver-type curve, a headphone correction
// published as a curve and the EQ in graphic mode are all on: one feature
// file each, each with its own `GraphicEQ:` line. Equalizer APO runs all
// three; this resolver used to keep only the last one it read.
void every_graphic_curve_is_kept() {
  std::printf("every graphic curve is kept, in file order\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: fluideq.txt\r\n";
  files[L"C:\\cfg\\fluideq.txt"] =
      "Device: {AAAA}\r\nChannel: all\r\nInclude: fluideq-device-a.txt\r\n";
  files[L"C:\\cfg\\fluideq-device-a.txt"] =
      "Include: fluideq-a-driver.txt\r\nInclude: fluideq-a-headphone.txt\r\n"
      "Include: fluideq-a-eq.txt\r\nPreamp: -4 dB\r\n";
  files[L"C:\\cfg\\fluideq-a-driver.txt"] = "GraphicEQ: 20 1; 20000 1\r\n";
  files[L"C:\\cfg\\fluideq-a-headphone.txt"] =
      "GraphicEQ: 20 0; 1000 -3; 20000 0\r\n";
  files[L"C:\\cfg\\fluideq-a-eq.txt"] = "GraphicEQ: 100 2; 10000 -2\r\n";
  const auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Headphones"},
                                   provider(files));
  CHECK(chain.matched);
  CHECK(chain.graphic_curves.size() == 3);
  CHECK(chain.graphic_curves.size() == 3 &&
        chain.graphic_curves[0].size() == 2 &&
        chain.graphic_curves[0][0].gain_db == 1.0 &&
        chain.graphic_curves[1].size() == 3 &&
        chain.graphic_curves[1][1].gain_db == -3.0 &&
        chain.graphic_curves[2].size() == 2 &&
        chain.graphic_curves[2][1].gain_db == -2.0);
  CHECK(chain.preamp_db == -4.0);
}

void neutral_root_is_passthrough() {
  std::printf("neutral root is passthrough\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: fluideq.txt\r\n";
  files[L"C:\\cfg\\fluideq.txt"] = "# Generated by FluidEQ.\r\n# Neutral.\r\n";
  const auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(!chain.matched);
  CHECK(chain.bands.empty());
}

void missing_root_is_passthrough() {
  std::printf("missing root is passthrough\n");
  const auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider({}));
  CHECK(!chain.matched);
}

/**
 * A missing rack file means "no rack", which is what makes deleting it the
 * cure for a rack that outlived an engine switch: the neutral root cannot
 * silence the rack, because the rack is read before the config tree and
 * outside every `Device:` guard.
 */
void rack_file_absence_means_no_rack() {
  std::printf("rack file absence means no rack\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: fluideq.txt\r\n";
  files[L"C:\\cfg\\fluideq.txt"] = "# Generated by FluidEQ.\r\n# Neutral.\r\n";
  const auto without = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(without.dsp_values.empty());

  files[L"C:\\cfg\\fluideq-dsp.txt"] =
      "# FluidEQ Engine DSP chain v1\r\n1 0.5 -2\r\n";
  const auto with_rack = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(with_rack.dsp_values.size() == 3);
  CHECK(with_rack.dsp_values[1] == 0.5);
  // The neutral root still silences the EQ — only the rack survives it.
  CHECK(!with_rack.matched);
}

void device_pattern_rules() {
  std::printf("device pattern rules\n");
  const Endpoint endpoint{L"{ABCD-1}", L"Speakers (2- Realtek Audio)"};
  CHECK(device_matches("all", endpoint));
  CHECK(device_matches("{abcd-1}", endpoint));
  CHECK(device_matches("Realtek", endpoint));
  CHECK(!device_matches("{FFFF}", endpoint));
  CHECK(!device_matches("Headphones", endpoint));
}

void include_cannot_escape_or_loop() {
  std::printf("include cannot escape or loop\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: ..\\evil.txt\r\nInclude: loop.txt\r\nPreamp: -1\r\n";
  files[L"C:\\evil.txt"] = "Preamp: -40\r\n";
  files[L"C:\\cfg\\loop.txt"] = "Include: loop.txt\r\nFilter 1: ON PK Fc 100 Hz Gain 1 dB Q 1\r\n";
  const auto chain = resolve_chain(L"C:\\cfg", {L"{A}", L"X"}, provider(files));
  CHECK(chain.preamp_db == -1.0);
  CHECK(chain.bands.size() == 1);  // loop.txt read once
}

void include_depth_is_limited() {
  std::printf("include depth is limited\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Include: d1.txt\r\n";
  for (int n = 1; n <= 9; ++n) {
    const std::wstring path = L"C:\\cfg\\d" + std::to_wstring(n) + L".txt";
    files[path] = "Preamp: -" + std::to_string(n) + "\r\nInclude: d" +
                  std::to_string(n + 1) + ".txt\r\n";
  }
  const auto chain = resolve_chain(L"C:\\cfg", {L"{A}", L"X"}, provider(files));
  // Depth is capped at 8 open frames (root config.txt + 7 Include levels):
  // d7.txt is the 8th and last frame opened, so its "Preamp: -7" is the last
  // one applied, and d7.txt's own "Include: d8.txt" is skipped rather than
  // followed — d8.txt is never opened. See resolve_chain's doc comment.
  CHECK(chain.preamp_db == -7.0);
  CHECK(std::find(chain.files_read.begin(), chain.files_read.end(),
                  L"C:\\cfg\\d7.txt") != chain.files_read.end());
  CHECK(std::find(chain.files_read.begin(), chain.files_read.end(),
                  L"C:\\cfg\\d8.txt") == chain.files_read.end());
}

void filter_grammar() {
  std::printf("filter grammar\n");
  CHECK(parse_filter("ON PK Fc 1000 Hz Gain -3 dB Q 1.41")->quality == 1.41);
  CHECK(parse_filter("ON LS Fc 80 Hz Gain 1 dB Q 0.7")->type == FilterType::LSC);
  CHECK(parse_filter("ON HPQ Fc 30 Hz Q 0.71")->gain_db == 0.0);
  CHECK(!parse_filter("OFF PK Fc 1 Hz Gain 1 dB Q 1"));
  CHECK(!parse_filter("ON XX Fc 100 Hz Gain -3 dB Q 1"));
  CHECK(!parse_filter("ON PK Fc nope Hz Gain -3 dB Q 1"));
  CHECK(!parse_filter("ON PK Fc 100 Hz Gain -3 dB Q 0"));
  const auto bw = parse_filter("ON PK Fc 100 Hz Gain -3 dB BW Oct 1");
  CHECK(bw && std::abs(bw->quality - 1.4142135) < 1e-6);
}

// `from_chars` reads "nan" and "inf" as numbers. One of them in a gain, a Q
// or a preamp turned every sample of the output into NaN and stayed latched
// in the filter history; nothing FluidEQ writes is ever anything but finite.
void numbers_that_are_not_finite_are_refused() {
  std::printf("nan and inf are not numbers this grammar takes\n");
  CHECK(!parse_filter("ON PK Fc 1000 Hz Gain nan dB Q 1"));
  CHECK(!parse_filter("ON PK Fc inf Hz Gain 3 dB Q 1"));
  CHECK(!parse_filter("ON PK Fc 1000 Hz Gain 3 dB Q -inf"));
  CHECK(!parse_filter("ON PK Fc 1000 Hz Gain 3 dB BW Oct nan"));
  CHECK(parse_graphic("20 inf; 1000 0").empty());
  CHECK(parse_graphic("nan 0; 1000 0").empty());
  // The positive control, so the refusals above cannot be passing on a
  // grammar that refuses everything.
  CHECK(parse_filter("ON PK Fc 1000 Hz Gain 3 dB Q 1").has_value());

  Files files;
  files[L"C:\\cfg\\config.txt"] = "Preamp: nan dB\r\n";
  const auto nan_preamp =
      resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(nan_preamp.preamp_db == 0.0);
  CHECK(!nan_preamp.matched);
}

void graphic_and_preamp_grammar() {
  std::printf("graphic and preamp grammar\n");
  const auto points = parse_graphic("20 -2.5; 1000 0; 20000 3");
  CHECK(points.size() == 3 && points[2].gain_db == 3.0);
  CHECK(parse_graphic("20 -2.5; nope").empty());
  const auto lines = tokenize("Preamp: -6\nPreamp:-2.5 dB\n# c\n\nFilter 1: ON PK Fc 1 Hz Gain 1 dB Q 1 # trailing\n");
  CHECK(lines.size() == 3);
  CHECK(lines[0].command == "Preamp" && lines[0].body == "-6");
  CHECK(lines[2].command == "Filter" && lines[2].body == "ON PK Fc 1 Hz Gain 1 dB Q 1");
}

void utf16_with_bom_is_read() {
  std::printf("utf16 with bom is read\n");
  const char16_t text[] = u"\uFEFFPreamp: -1 dB\n";
  const auto lines = tokenize(std::string_view(reinterpret_cast<const char*>(text), sizeof(text) - sizeof(char16_t)));
  CHECK(lines.size() == 1 && lines[0].body == "-1 dB");
}

void engine_comments_keep_manual_and_custom_preamp_semantics() {
  Files files;
  files[L"C:\\cfg\\config.txt"] =
      "Device: {AAAA}\nPreamp: -12 dB\n# FluidEQAutoPreamp: ON\n"
      "# FluidEQCurveStage: ON\n";
  auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(chain.matched && chain.output_guard && chain.auto_preamp);
  CHECK(chain.preamp_db == 0 && chain.stable_graphic);
  // Auto normalize starts from the level the app sized for the curve.
  CHECK(chain.auto_preamp_start_db == -12);
  auto other = resolve_chain(L"C:\\cfg", {L"{BBBB}", L"Other"}, provider(files));
  CHECK(!other.matched && !other.output_guard && !other.stable_graphic);
  files[L"C:\\cfg\\config.txt"] += "Include: custom.txt\n";
  files[L"C:\\cfg\\custom.txt"] = "Preamp: -3 dB\n";
  chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(chain.auto_preamp && chain.preamp_db == -3);
  CHECK(chain.auto_preamp_start_db == -12);
  files[L"C:\\cfg\\config.txt"] = "Preamp: -7 dB\n# FluidEQAutoPreamp: OFF\n";
  chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(chain.output_guard && !chain.auto_preamp && chain.preamp_db == -7);
  files[L"C:\\cfg\\config.txt"] = "Preamp: -7 dB\n# ordinary comment FluidEQAutoPreamp: ON\n";
  chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(!chain.output_guard && chain.preamp_db == -7);
}

/**
 * Game mode from the EQ side: the line the app writes into a device's block
 * while its voicing is Games. Guarded by the device like every other line,
 * only ever switched ON by one, and never read from a plain comment.
 */
void game_mode_comes_from_the_device_block() {
  Files files;
  files[L"C:\\cfg\\config.txt"] =
      "Device: {AAAA}\nPreamp: -3 dB\n# FluidEQLowLatency: ON\n"
      "Device: {BBBB}\nPreamp: -3 dB\n";
  auto games = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Headset"}, provider(files));
  CHECK(games.matched && games.low_latency);
  // POSITIVE CONTROL: the other device's block says nothing of it.
  auto other = resolve_chain(L"C:\\cfg", {L"{BBBB}", L"Speakers"}, provider(files));
  CHECK(other.matched && !other.low_latency);
  // An OFF somewhere later cannot take away what a block asked for.
  files[L"C:\\cfg\\config.txt"] =
      "Device: all\n# FluidEQLowLatency: ON\n# FluidEQLowLatency: OFF\n";
  games = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Headset"}, provider(files));
  CHECK(games.low_latency);
  // And an ordinary comment that happens to mention it is a comment.
  files[L"C:\\cfg\\config.txt"] = "Preamp: -3 dB\n# see FluidEQLowLatency: ON\n";
  games = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Headset"}, provider(files));
  CHECK(!games.low_latency);
}

void phase_scopes_follow_includes_without_leaking() {
  Files files;
  files[L"C:\\cfg\\config.txt"] =
      "Device: {AAAA}\nInclude: eq.txt\nInclude: curve.txt\n"
      "Filter: ON PK Fc 700 Hz Gain 2 dB Q 2\n"
      "Device: {BBBB}\nInclude: excluded.txt\n";
  files[L"C:\\cfg\\eq.txt"] = "# FluidEQEqLayer: ON\nInclude: nested.txt\n";
  files[L"C:\\cfg\\nested.txt"] =
      "Filter: ON PK Fc 1000 Hz Gain 6 dB Q 2\nGraphicEQ: 20 2; 20000 -1\n";
  files[L"C:\\cfg\\curve.txt"] =
      "# FluidEQCurveLayer: ON\nFilter: ON PK Fc 4000 Hz Gain -5 dB Q 4\n"
      "GraphicEQ: 20 -1; 20000 3\n";
  files[L"C:\\cfg\\excluded.txt"] =
      "# FluidEQEqLayer: ON\nFilter: ON PK Fc 300 Hz Gain 20 dB Q 2\n";
  const auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(chain.bands.size() == 3);
  CHECK(chain.bands[0].user_eq && !chain.bands[0].curve_layer);
  CHECK(chain.bands[1].curve_layer && !chain.bands[1].user_eq);
  CHECK(!chain.bands[2].user_eq && !chain.bands[2].curve_layer);
  CHECK(chain.graphic_curves.size() == 2);
  CHECK(chain.eq_graphic_curves.size() == 1 && chain.eq_graphic_curves[0][0].gain_db == 2);
  CHECK(chain.comparison_curves.size() == 1 && chain.comparison_curves[0][0].gain_db == -1);
  CHECK(chain.minimum_curve_phase && chain.minimum_eq_phase);
}

void game_mode_metadata_keeps_the_rack_compatible() {
  Files files;
  files[L"C:\\cfg\\fluideq-dsp.txt"] =
      "# FluidEQ Engine DSP chain v1\n# FluidEQLowLatency: ON\n1 2 3\n";
  auto chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(chain.low_latency);
  CHECK(chain.dsp_values == std::vector<double>({1, 2, 3}));
  files[L"C:\\cfg\\fluideq-dsp.txt"] =
      "# FluidEQ Engine DSP chain v1\n1 2 3\n";
  chain = resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  CHECK(!chain.low_latency);
  CHECK(chain.dsp_values == std::vector<double>({1, 2, 3}));
}

void official_phase_files_are_independent_and_default_to_minimum() {
  Files files;
  files[L"C:\\cfg\\config.txt"] = "Preamp: -2 dB\n";
  files[L"C:\\cfg\\fluideq-curve-comparison.txt"] = "A\n";
  const auto read = [&files]() {
    return resolve_chain(L"C:\\cfg", {L"{AAAA}", L"Speakers"}, provider(files));
  };
  CHECK(read().minimum_curve_phase && read().minimum_eq_phase);
  files[L"C:\\cfg\\fluideq-curve-phase.txt"] = "A\r\n";
  CHECK(!read().minimum_curve_phase && read().minimum_eq_phase);
  files[L"C:\\cfg\\fluideq-curve-phase.txt"] = "B\n";
  files[L"C:\\cfg\\fluideq-eq-phase.txt"] = "A\n";
  CHECK(read().minimum_curve_phase && !read().minimum_eq_phase);
  files[L"C:\\cfg\\fluideq-eq-phase.txt"] = "invalid\n";
  CHECK(read().minimum_curve_phase && read().minimum_eq_phase);
}

}  // namespace

// The analog-matched design is asked for file by file: a layer's directive
// governs the filters after it in that file and in what it includes, and
// never the next file its parent includes — the headphone correction sits
// beside the EQ layer in one device file and has to stay on the cookbook
// AutoEQ fitted it with (0.14 dB from its fit, 0.89 dB built matched).
void filter_design_scopes_follow_includes_without_leaking() {
  std::printf("filter design scopes follow includes without leaking\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] =
      "Include: eq.txt\r\nInclude: headphone.txt\r\n"
      "Filter 9: ON PK Fc 9000 Hz Gain 1 dB Q 1\r\n";
  files[L"C:\\cfg\\eq.txt"] =
      "Filter 1: ON PK Fc 100 Hz Gain 2 dB Q 1\r\n"
      "# FluidEQFilterDesign: MATCHED\r\n"
      "Filter 2: ON PK Fc 16000 Hz Gain 6 dB Q 2\r\n"
      "Include: eq-more.txt\r\n"
      "# FluidEQFilterDesign: COOKBOOK\r\n"
      "Filter 3: ON PK Fc 12000 Hz Gain 3 dB Q 2\r\n";
  files[L"C:\\cfg\\eq-more.txt"] = "Filter 4: ON PK Fc 10000 Hz Gain 4 dB Q 2\r\n";
  files[L"C:\\cfg\\headphone.txt"] = "Filter 5: ON PK Fc 8474 Hz Gain -7 dB Q 1\r\n";
  const Chain chain = resolve_chain(L"C:\\cfg", Endpoint{L"{X}", L"Test"},
                                    provider(files));
  CHECK(chain.bands.size() == 6);
  if (chain.bands.size() != 6) {
    return;
  }
  // POSITIVE CONTROL: the directive does switch the design on, so the
  // cookbook everywhere else is the scope at work rather than a dead line.
  CHECK(chain.bands[1].matched);  // after the directive, same file
  CHECK(chain.bands[2].matched);  // inherited by an include
  CHECK(!chain.bands[0].matched);  // before it
  CHECK(!chain.bands[3].matched);  // switched back in the same file
  CHECK(!chain.bands[4].matched);  // a sibling file: the correction
  CHECK(!chain.bands[5].matched);  // the parent, after the include returned
}

// Classic, per group: the EQ layer's bands on one file, every other layer
// FluidEQ writes on the other, the headphone correction never matched at all.
void treble_choice_keeps_a_group_on_the_cookbook() {
  std::printf("the treble choice keeps a group on the cookbook\n");
  const auto resolve = [](const char* eq_choice, const char* curve_choice) {
    Files files;
    files[L"C:\\cfg\\config.txt"] =
        "Include: eq.txt\r\nInclude: preset.txt\r\nInclude: headphone.txt\r\n";
    files[L"C:\\cfg\\eq.txt"] =
        "# FluidEQEqLayer: ON\r\n# FluidEQFilterDesign: MATCHED\r\n"
        "Filter 1: ON PK Fc 16000 Hz Gain 6 dB Q 2\r\n";
    files[L"C:\\cfg\\preset.txt"] =
        "# FluidEQCurveLayer: ON\r\n# FluidEQFilterDesign: MATCHED\r\n"
        "Filter 1: ON PK Fc 10000 Hz Gain 3 dB Q 1\r\n";
    files[L"C:\\cfg\\headphone.txt"] =
        "# FluidEQCurveLayer: ON\r\nFilter 1: ON PK Fc 8474 Hz Gain -7 dB Q 1\r\n";
    if (eq_choice != nullptr) files[L"C:\\cfg\\fluideq-eq-treble.txt"] = eq_choice;
    if (curve_choice != nullptr) files[L"C:\\cfg\\fluideq-curve-treble.txt"] = curve_choice;
    return resolve_chain(L"C:\\cfg", Endpoint{L"{X}", L"Test"}, provider(files));
  };
  const auto matched = [](const Chain& chain) {
    std::vector<bool> out;
    for (const Band& band : chain.bands) out.push_back(band.matched);
    return out;
  };
  // POSITIVE CONTROL: with no choice written, the layers that ask for it
  // play matched, so every false below is the choice's doing.
  CHECK(matched(resolve(nullptr, nullptr)) == std::vector<bool>{true, true, false});
  CHECK(matched(resolve("classic\r\n", nullptr)) == std::vector<bool>{false, true, false});
  CHECK(matched(resolve(nullptr, "classic")) == std::vector<bool>{true, false, false});
  CHECK(matched(resolve("classic", "classic")) == std::vector<bool>{false, false, false});
  CHECK(matched(resolve("precise", "precise")) == std::vector<bool>{true, true, false});
  // Anything but the exact word leaves Precise.
  CHECK(matched(resolve("Classical", "classic please")) == std::vector<bool>{true, true, false});
  const Chain chosen = resolve("classic", nullptr);
  CHECK(chosen.classic_eq_treble && !chosen.classic_curve_treble);
}

// The cuts' file, included after the preamp as `deviceProfiles.ts` writes it,
// names no layer and asks for no design: every section is a plain cookbook band.
void cuts_file_is_plain_cookbook_bands() {
  std::printf("the cuts file is plain cookbook bands\n");
  Files files;
  files[L"C:\\cfg\\config.txt"] =
      "Include: eq.txt\r\nPreamp: -3 dB\r\nInclude: fluideq-cuts.txt\r\n";
  files[L"C:\\cfg\\eq.txt"] = "# FluidEQEqLayer: ON\r\n# FluidEQFilterDesign: MATCHED\r\n"
                              "Filter 1: ON PK Fc 1000 Hz Gain 3 dB Q 1\r\n";
  files[L"C:\\cfg\\fluideq-cuts.txt"] =
      "# Cuts\r\nFilter 1: ON HPQ Fc 20 Hz Q 0.5412\r\n"
      "Filter 2: ON HPQ Fc 20 Hz Q 1.3066\r\nFilter 3: ON LPQ Fc 20000 Hz Q 0.7071\r\n";
  const Chain chain = resolve_chain(L"C:\\cfg", Endpoint{L"{X}", L"Test"}, provider(files));
  CHECK(chain.bands.size() == 4 && chain.preamp_db == -3.0);
  // POSITIVE CONTROL: the EQ's own band is matched and in its layer.
  CHECK(chain.bands[0].matched && chain.bands[0].user_eq);
  CHECK(std::none_of(chain.bands.begin() + 1, chain.bands.end(), [](const Band& band) {
    return band.matched || band.user_eq || band.curve_layer;
  }));
  CHECK(chain.bands[1].type == FilterType::HPQ && chain.bands[3].type == FilterType::LPQ);
}

// A device's layers as `deviceProfiles.ts` writes them since the Tone became
// a layer: every file in Your EQ's group but the headphone correction
// (`layerGroupOf`), each asking for the matched design. Your EQ's Treble row
// then moves the bands, the Tone and a preset together, and the correction
// alone follows the Corrections row, in its bands and its sampled curve.
void every_layer_but_the_correction_plays_by_your_eqs_row() {
  std::printf("every layer but the correction plays by Your EQ's row\n");
  const auto resolve = [](const char* eq_choice) {
    Files files;
    files[L"C:\\cfg\\config.txt"] =
        "Include: eq.txt\r\nInclude: tone.txt\r\nInclude: preset.txt\r\n"
        "Include: headphone.txt\r\n";
    files[L"C:\\cfg\\eq.txt"] =
        "# FluidEQEqLayer: ON\r\n# FluidEQFilterDesign: MATCHED\r\n"
        "Filter 1: ON PK Fc 16000 Hz Gain 6 dB Q 2\r\n";
    files[L"C:\\cfg\\tone.txt"] =
        "# FluidEQEqLayer: ON\r\n# FluidEQFilterDesign: MATCHED\r\n"
        "Filter 1: ON LSC Fc 100 Hz Gain 4 dB Q 0.71\r\n";
    files[L"C:\\cfg\\preset.txt"] =
        "# FluidEQEqLayer: ON\r\n# FluidEQFilterDesign: MATCHED\r\n"
        "Filter 1: ON PK Fc 10000 Hz Gain 3 dB Q 1\r\nGraphicEQ: 20 2; 20000 -2\r\n";
    files[L"C:\\cfg\\headphone.txt"] =
        "# FluidEQCurveLayer: ON\r\n# FluidEQFilterDesign: MATCHED\r\n"
        "Filter 1: ON PK Fc 8474 Hz Gain -7 dB Q 1\r\nGraphicEQ: 20 -3; 20000 1\r\n";
    if (eq_choice != nullptr) files[L"C:\\cfg\\fluideq-eq-treble.txt"] = eq_choice;
    return resolve_chain(L"C:\\cfg", Endpoint{L"{X}", L"Test"}, provider(files));
  };
  const Chain precise = resolve(nullptr);
  CHECK(precise.bands.size() == 4);
  CHECK(precise.bands[0].user_eq && precise.bands[1].user_eq && precise.bands[2].user_eq);
  CHECK(precise.bands[3].curve_layer && !precise.bands[3].user_eq);
  // POSITIVE CONTROL: all four ask for it and play matched with no choice
  // written, so every false below is Your EQ's Classic.
  CHECK(std::all_of(precise.bands.begin(), precise.bands.end(),
                    [](const Band& band) { return band.matched; }));
  const Chain classic = resolve("classic");
  CHECK(!classic.bands[0].matched && !classic.bands[1].matched && !classic.bands[2].matched);
  CHECK(classic.bands[3].matched);
  // The preset's sampled curve is Your EQ's, the correction's the other row's.
  CHECK(precise.eq_graphic_curves.size() == 1 && precise.eq_graphic_curves[0][0].gain_db == 2);
  CHECK(precise.comparison_curves.size() == 1 &&
        precise.comparison_curves[0][0].gain_db == -3);
}

int main() {
  std::printf("fluideq engine config\n");
  follows_includes_and_device_guards();
  every_graphic_curve_is_kept();
  neutral_root_is_passthrough();
  missing_root_is_passthrough();
  rack_file_absence_means_no_rack();
  device_pattern_rules();
  include_cannot_escape_or_loop();
  include_depth_is_limited();
  filter_grammar();
  numbers_that_are_not_finite_are_refused();
  graphic_and_preamp_grammar();
  utf16_with_bom_is_read();
  engine_comments_keep_manual_and_custom_preamp_semantics();
  game_mode_comes_from_the_device_block();
  game_mode_metadata_keeps_the_rack_compatible();
  phase_scopes_follow_includes_without_leaking();
  official_phase_files_are_independent_and_default_to_minimum();
  filter_design_scopes_follow_includes_without_leaking();
  treble_choice_keeps_a_group_on_the_cookbook();
  cuts_file_is_plain_cookbook_bands();
  every_layer_but_the_correction_plays_by_your_eqs_row();
  if (g_failures == 0) {
    std::printf("config: ok\n");
    return 0;
  }
  std::printf("\n%d check(s) failed\n", g_failures);
  return 1;
}
