# Writes `shipped_dlls.h`: the SHA-256 of every DLL the setup helper installs,
# taken from this build's own output, for `digest.cpp` to check them against.
#
# Run as a script after the engine is linked (-DENGINE=<the engine DLL>,
# -DOUTPUT=<the header>). The runtime DLLs are read from the same folder, where
# `build-native-dsp.ts` copies them before the build starts; a build without
# them (plain CMake, no script) ships a helper that will install only the
# engine and refuse a runtime DLL it has no digest for.
#
# The header is rewritten only when a digest changes, so an unchanged engine
# does not recompile the helper.

get_filename_component(dir "${ENGINE}" DIRECTORY)
set(entries "")
foreach(name FluidEQ-Engine.dll msvcp140.dll vcruntime140.dll vcruntime140_1.dll)
  if(EXISTS "${dir}/${name}")
    file(SHA256 "${dir}/${name}" digest)
    string(APPEND entries "    {L\"${name}\", \"${digest}\"},\n")
  endif()
endforeach()
if(entries STREQUAL "")
  message(FATAL_ERROR "shipped_dlls.cmake: ${ENGINE} does not exist")
endif()

set(content "// Generated by native/system-apo/setup/shipped_dlls.cmake. Do not edit.
#ifndef FLUIDEQ_ENGINE_SETUP_SHIPPED_DLLS_H
#define FLUIDEQ_ENGINE_SETUP_SHIPPED_DLLS_H

namespace fluideq_engine::setup {

struct ShippedDll {
  const wchar_t* name;
  const char* sha256;
};

inline constexpr ShippedDll kShippedDlls[] = {
${entries}};

}  // namespace fluideq_engine::setup

#endif  // FLUIDEQ_ENGINE_SETUP_SHIPPED_DLLS_H
")

if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" existing)
  if(existing STREQUAL content)
    return()
  endif()
endif()
file(WRITE "${OUTPUT}" "${content}")
