// Generated by .erb/scripts/generate-room-profiles-fixture.ts; do not edit.
#pragma once
// sizeM, walls, distanceM, centreDb, subDb, angles x7, levels x7, distances x7,
// mutes x8, bassManagement, crossoverHz, musicUpmix, upmixAmount,
// rendererVersion, earlyReflectionDb, ambienceMix, ambienceDecayS,
// ambienceDampingHz, preservePosition.
struct RoomProfileFixture {
  const char* id;
  double values[44];
};
inline constexpr RoomProfileFixture kRoomProfiles[] = {
  {"referenceV2", {3.6, 0.65, 1.2, 0, 0, -30, 30, 0, -100, 100, -140, 140, 0, 0, 0, 0, 0, 0, 0, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 80, 0, 0.6, 2, -16, 0, 0.2, 8000, 1}},
  {"musicSpaceV2", {5, 0.5, 1.8, 0, 0, -32, 32, 0, -100, 100, -140, 140, 0, 0, 0, -2, -2, -3, -3, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 0, 0, 0, 0, 0, 0, 0, 0, 1, 80, 1, 0.35, 2, -12, 0.3, 0.35, 7000, 1}},
  {"cinemaV2", {8, 0.4, 2.2, 1.5, 1, -30, 30, 0, -105, 105, -145, 145, 0, 0, 0, 0, 0, 0, 0, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 80, 1, 0.5, 2, -8, 0.4, 0.7, 5000, 1}},
  {"gameWorldV2", {5, 0.55, 1.6, 0, 0.5, -30, 30, 0, -95, 95, -140, 140, 0, 0, 0, 0, 0, 0, 0, 1.6, 1.6, 1.6, 1.6, 1.6, 1.6, 1.6, 0, 0, 0, 0, 0, 0, 0, 0, 1, 80, 0, 0.6, 2, -14, 0.3, 0.25, 8000, 1}},
  {"competitiveV2", {3, 0.85, 1, 0, 0, -30, 30, 0, -90, 90, -135, 135, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 80, 0, 0.6, 2, -60, 0, 0.1, 10000, 1}},
  {"liveVenueV2", {11, 0.3, 2.4, 0, -1, -28, 28, 0, -100, 100, -140, 140, 0, 0, 0, -2, -2, -3, -3, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 0, 0, 0, 0, 0, 0, 0, 0, 1, 80, 1, 0.55, 2, -4, 0.6, 1.2, 4500, 1}},
};
