packages:
  - .
  - release/app

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  edgedriver: true
  electron: true
  electron-chromedriver: true
  electron-winstaller: true
  geckodriver: true
  lzma-native: true
  onnxruntime-node: false
  protobufjs: true
  sharp: false
  unrs-resolver: true

overrides:
  '@types/d3-dispatch': 3.0.7
  adm-zip: 0.6.0
  eslint: 8.57.1
  fast-uri: 3.1.6
  sharp: 0.35.0
  typescript: 6.0.3

storeDir: .pnpm-store
confirmModulesPurge: false
patchedDependencies:
  '@huggingface/transformers@3.7.6': patches/@huggingface__transformers@3.7.6.patch
  music-metadata@11.14.0: patches/music-metadata@11.14.0.patch
