/** @jest-environment node */
/* FluidEQ — GPL-3.0-or-later */

/**
 * Quitting FluidEQ left every output EQ'd: both engines run inside Windows'
 * audio service and keep applying what they last read. These pin the reset
 * that now runs on the way out — and the one thing it must never do, which is
 * leave a config the next launch reads back as the user's EQ being gone.
 */

import fs from 'fs';
import os from 'os';
import path from 'path';
import {
  flushPendingWrites,
  scheduleWrite,
  scheduleWriteOperation,
  sealDirectory,
  writeFileNow,
} from '../../../main/asyncWriter';
import {
  resetEngineAtSessionEnd,
  resetEngineForQuit,
} from '../../../main/engineQuitReset';
import { DISABLED_ROOT_TEXT } from '../../../main/deviceProfiles';
import { readApoDeviceChain } from '../../../main/apoConfigReader';

const DEVICE = '{0.0.0.00000000}.{11111111-2222-3333-4444-555555555555}';
const LIVE_ROOT = [
  '# Generated by FluidEQ. Changes are overwritten automatically.',
  `Device: ${DEVICE}`,
  'Include: fluideq-device-0123456789ab.txt',
].join('\r\n');
const DEVICE_FILE = 'Preamp: -3 dB\r\nFilter 1: ON PK Fc 1000 Hz Gain 3 dB Q 1';

describe('resetting the engine as FluidEQ goes', () => {
  let directory: string;
  const root = () => path.join(directory, 'fluideq.txt');
  const rack = () => path.join(directory, 'fluideq-dsp.txt');

  beforeEach(() => {
    directory = fs.mkdtempSync(path.join(os.tmpdir(), 'fluideq-quit-'));
    fs.writeFileSync(root(), LIVE_ROOT);
    fs.writeFileSync(
      path.join(directory, 'fluideq-device-0123456789ab.txt'),
      DEVICE_FILE,
    );
    fs.writeFileSync(rack(), 'rack 1 2 3');
  });

  afterEach(async () => {
    await flushPendingWrites().catch(() => undefined);
    fs.rmSync(directory, { recursive: true, force: true });
  });

  it('turns the engine off and takes its rack away on quit', async () => {
    // A positive control: before the reset the device really is EQ'd.
    expect(readApoDeviceChain(directory, DEVICE)).toBeDefined();

    await resetEngineForQuit(directory);

    expect(fs.readFileSync(root(), 'utf8')).toBe(DISABLED_ROOT_TEXT);
    expect(fs.existsSync(rack())).toBe(false);
  });

  it('leaves nothing the next launch could adopt over the saved EQ', async () => {
    await resetEngineForQuit(directory);
    expect(readApoDeviceChain(directory, DEVICE)).toBeUndefined();
  });

  it('lets a write already on its way land first, then overwrites it', async () => {
    const late = scheduleWrite(root(), `${LIVE_ROOT}\r\n# the end of a drag`);
    await resetEngineForQuit(directory);
    await late;
    expect(fs.readFileSync(root(), 'utf8')).toBe(DISABLED_ROOT_TEXT);
  });

  it('refuses every write asked for after the reset', async () => {
    await resetEngineForQuit(directory);

    await scheduleWrite(root(), LIVE_ROOT);
    await scheduleWrite(rack(), 'rack 4 5 6');
    const work = jest.fn(async () => undefined);
    await scheduleWriteOperation(directory, work);
    await flushPendingWrites();

    expect(fs.readFileSync(root(), 'utf8')).toBe(DISABLED_ROOT_TEXT);
    expect(fs.existsSync(rack())).toBe(false);
    expect(work).not.toHaveBeenCalled();
  });

  it('does the same synchronously when Windows ends the session', () => {
    resetEngineAtSessionEnd(directory);

    expect(fs.readFileSync(root(), 'utf8')).toBe(DISABLED_ROOT_TEXT);
    expect(fs.existsSync(rack())).toBe(false);
    expect(readApoDeviceChain(directory, DEVICE)).toBeUndefined();
  });

  it('copes with an engine that never had a rack', async () => {
    fs.rmSync(rack());
    await expect(resetEngineForQuit(directory)).resolves.toBeUndefined();
    expect(fs.readFileSync(root(), 'utf8')).toBe(DISABLED_ROOT_TEXT);
  });
});

describe('sealing a directory', () => {
  let sealed: string;
  let open: string;

  beforeEach(() => {
    sealed = fs.mkdtempSync(path.join(os.tmpdir(), 'fluideq-sealed-'));
    open = fs.mkdtempSync(path.join(os.tmpdir(), 'fluideq-open-'));
    sealDirectory(sealed);
  });

  afterEach(async () => {
    await flushPendingWrites().catch(() => undefined);
    fs.rmSync(sealed, { recursive: true, force: true });
    fs.rmSync(open, { recursive: true, force: true });
  });

  it('refuses writes inside it and nowhere else', async () => {
    await scheduleWrite(path.join(sealed, 'a.txt'), 'refused');
    await scheduleWrite(path.join(open, 'a.txt'), 'written');

    expect(fs.existsSync(path.join(sealed, 'a.txt'))).toBe(false);
    expect(fs.readFileSync(path.join(open, 'a.txt'), 'utf8')).toBe('written');
  });

  it('does not seal a sibling whose name merely starts the same', async () => {
    const sibling = `${sealed}-sibling`;
    fs.mkdirSync(sibling);
    try {
      await scheduleWrite(path.join(sibling, 'a.txt'), 'written');
      expect(fs.readFileSync(path.join(sibling, 'a.txt'), 'utf8')).toBe(
        'written',
      );
    } finally {
      fs.rmSync(sibling, { recursive: true, force: true });
    }
  });

  it('still takes the one write made past it on purpose', async () => {
    await writeFileNow(path.join(sealed, 'a.txt'), 'final');
    expect(fs.readFileSync(path.join(sealed, 'a.txt'), 'utf8')).toBe('final');
  });
});
