/*
<AQUA: System-wide parametric audio equalizer interface>
Copyright (C) <2023>  <AQUA Dev Team>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

import {
  adoptBlock,
  describeAudibleChain,
  findBlockForDevice,
  hasChainDrifted,
  splitConfigBlocks,
} from '../../../common/apoSync';
import {
  AutoEqFormat,
  FilterTypeEnum,
  IFiltersMap,
  IState,
  getDefaultState,
} from '../../../common/constants';
import { stateToString } from '../../../main/flush';

const GUID = '{2de2e800-7980-4b45-a318-34276fe3d3b4}';

const band = (
  id: string,
  frequency: number,
  gain: number,
  quality = 1,
  type = FilterTypeEnum.PK,
) => ({ id, frequency, gain, quality, type });

const withBands = (...bands: ReturnType<typeof band>[]): IFiltersMap => {
  const filters: IFiltersMap = {};
  bands.forEach((entry) => {
    filters[entry.id] = entry;
  });
  return filters;
};

describe('reading the Equalizer APO config back', () => {
  const CONFIG = [
    '# Generated by FluidEQ. Changes are overwritten automatically.',
    '',
    '# Neutral fallback for every output without an attached profile.',
    'Device: all',
    'Channel: all',
    '',
    '# Headphones -> Studio',
    `Device: ${GUID}`,
    'Channel: all',
    'Convolution: fluideq-ir-abc123.wav',
    'Preamp: -4.5 dB',
    'Filter 1: ON PK Fc 100 Hz Gain 3 dB Q 1',
    'Filter 2: ON HSC Fc 8000 Hz Gain -2 dB Q 0.7',
    '',
    '# Speakers -> Desk',
    'Device: {OTHER-GUID}',
    'Channel: all',
    'Preamp: 0 dB',
    'Filter 1: ON PK Fc 60 Hz Gain 5 dB Q 0.9',
  ].join('\r\n');

  it('splits a generated config into its device blocks', () => {
    const blocks = splitConfigBlocks(CONFIG);
    expect(blocks.map((b) => b.devicePattern)).toEqual([
      'all',
      GUID,
      '{OTHER-GUID}',
    ]);
  });

  it('picks the block that names the endpoint over the global one', () => {
    const blocks = splitConfigBlocks(CONFIG);
    const block = findBlockForDevice(blocks, GUID);
    expect(block?.devicePattern).toBe(GUID);
    expect(adoptBlock(block!)?.preAmp).toBe(-4.5);
  });

  it('falls back to the global block for an endpoint nothing names', () => {
    const blocks = splitConfigBlocks(CONFIG);
    expect(findBlockForDevice(blocks, '{UNKNOWN}')?.devicePattern).toBe('all');
  });

  it('reads a device block back into bands, preamp and impulse response', () => {
    const blocks = splitConfigBlocks(CONFIG);
    const adopted = adoptBlock(findBlockForDevice(blocks, GUID)!)!;

    expect(adopted.preAmp).toBe(-4.5);
    expect(adopted.convolutionFileName).toBe('fluideq-ir-abc123.wav');
    const bands = Object.values(adopted.filters).sort(
      (l, r) => l.frequency - r.frequency,
    );
    expect(bands.map((b) => [b.type, b.frequency, b.gain])).toEqual([
      [FilterTypeEnum.PK, 100, 3],
      [FilterTypeEnum.HSC, 8000, -2],
    ]);
  });

  it('treats the neutral fallback block as saying nothing', () => {
    // FluidEQ writes a bare Device/Channel pair for outputs with no profile.
    // Mistaking that for "the user cleared their EQ" would wipe a tuning on
    // every startup of a machine with a second output.
    const blocks = splitConfigBlocks(CONFIG);
    expect(adoptBlock(blocks[0])).toBeUndefined();
  });

  it('round-trips what stateToString writes without reporting drift', () => {
    // The whole feature rests on this: if reading back what we just wrote
    // looked like a change, FluidEQ would "adopt" its own output on every
    // launch and nothing would ever be stable.
    const state: IState = {
      ...getDefaultState(),
      preAmp: -6.4,
      isFlat: false,
      filters: withBands(
        band('a', 105, 5.4, 0.7, FilterTypeEnum.LSC),
        band('b', 2200, -3.1, 1.41),
        band('c', 30, 0, 0.71, FilterTypeEnum.HPQ),
      ),
    };

    const text = stateToString(state, undefined, GUID);
    const adopted = adoptBlock(splitConfigBlocks(text)[0])!;

    expect(hasChainDrifted(text, adopted)).toBe(false);
  });

  it('round-trips a GraphicEQ chain too', () => {
    const state: IState = {
      ...getDefaultState(),
      preAmp: -2,
      isFlat: false,
      eqFormat: AutoEqFormat.GRAPHIC,
      graphicEq: [
        { frequency: 20, gain: -1.2 },
        { frequency: 1000, gain: 0 },
        { frequency: 20000, gain: 2.5 },
      ],
    };

    const text = stateToString(state, undefined, GUID);
    const adopted = adoptBlock(splitConfigBlocks(text)[0])!;

    expect(adopted.eqFormat).toBe(AutoEqFormat.GRAPHIC);
    expect(hasChainDrifted(text, adopted)).toBe(false);
  });

  it('notices a band someone changed outside FluidEQ', () => {
    const state: IState = {
      ...getDefaultState(),
      preAmp: -3,
      isFlat: false,
      filters: withBands(band('a', 1000, 4)),
    };
    const edited = adoptBlock(
      splitConfigBlocks(
        [
          `Device: ${GUID}`,
          'Channel: all',
          'Preamp: -3 dB',
          'Filter 1: ON PK Fc 1000 Hz Gain 9 dB Q 1',
        ].join('\n'),
      )[0],
    )!;

    expect(hasChainDrifted(stateToString(state, undefined, GUID), edited)).toBe(
      true,
    );
  });

  it('notices an impulse response that appeared or vanished', () => {
    const state: IState = {
      ...getDefaultState(),
      preAmp: 0,
      isAutoPreAmpOn: false,
      isFlat: false,
      filters: withBands(band('a', 1000, 3)),
    };
    // stateToString only emits a Convolution line when the state carries one,
    // so the "same impulse response" case below needs a state that has it.
    const stateWithIr: IState = {
      ...state,
      convolution: {
        name: 'Someone else',
        filters: {},
        fileName: 'someone-elses.wav',
      },
    };
    const withIr = adoptBlock(
      splitConfigBlocks(
        [
          `Device: ${GUID}`,
          'Channel: all',
          'Convolution: someone-elses.wav',
          'Preamp: 0 dB',
          'Filter 1: ON PK Fc 1000 Hz Gain 3 dB Q 1',
        ].join('\n'),
      )[0],
    )!;

    expect(hasChainDrifted(stateToString(state, undefined, GUID), withIr)).toBe(
      true,
    );
    // Same chain, same impulse response: not a change.
    expect(
      hasChainDrifted(
        stateToString(stateWithIr, 'someone-elses.wav', GUID),
        withIr,
      ),
    ).toBe(false);
  });

  it('does not call a reordered chain a change', () => {
    // APO applies biquads in series and their order does not change the
    // magnitude response, so two configs listing the same bands in a different
    // order sound identical.
    const first = describeAudibleChain({
      preAmp: -3,
      filters: withBands(band('a', 100, 3), band('b', 8000, -2)),
    });
    const second = describeAudibleChain({
      preAmp: -3,
      filters: withBands(band('x', 8000, -2), band('y', 100, 3)),
    });
    expect(first).toBe(second);
  });
});
