/*
<FluidEQ: System-wide parametric audio equalizer interface>
Copyright (C) <2026>  <Ivan Carmenates Garcia>
SPDX-License-Identifier: GPL-3.0-or-later
*/

import { NO_GAIN_FILTER_TYPES } from '../constants';
import { EQ_BAND_COUNT, IEqBandSettings, IEqSettings } from './chain';

/**
 * Equalizer APO's ParametricEQ text, read and written.
 *
 * The format AutoEq, oratory1990, Squiglink and every headphone correction
 * database publishes in, which is the whole point: a curve someone downloads
 * for their headphones should load here, and a curve made here should paste
 * into `config.txt` and behave identically.
 *
 *     Preamp: -6.3 dB
 *     Filter 1: ON LSC Fc 105 Hz Gain 5.5 dB Q 0.70
 *     Filter 2: ON PK Fc 1200 Hz Gain -2.1 dB Q 1.41
 *     Filter 3: ON HPQ Fc 30 Hz Q 0.71
 *
 * Band pass, notch, low pass and high pass carry NO Gain token — APO's grammar
 * has no gain for those forms and a line that includes one is rejected
 * outright, which `apoRender.ts` already learned the hard way. Both directions
 * here honour that.
 */

/** Trailing zeros off: `3.5` rather than `3.50`, `4` rather than `4.00`. */
const round = (value: number) => Math.round(value * 100) / 100;

export const toApoText = (eq: IEqSettings): string => {
  const lines = eq.bands
    .filter((band) => band.enabled)
    .map((band, index) => {
      const head = `Filter ${index + 1}: ON ${band.type} Fc ${round(
        band.frequency,
      )} Hz`;
      const q = `Q ${round(band.quality)}`;
      return NO_GAIN_FILTER_TYPES.includes(band.type as never)
        ? `${head} ${q}`
        : `${head} Gain ${round(band.gainDb)} dB ${q}`;
    });
  // A preamp line even at 0: every tool that reads this format expects one,
  // and its absence has been read as "this file is not a ParametricEQ export".
  return [`Preamp: ${round(preampFor(eq))} dB`, ...lines].join('\n');
};

/**
 * Headroom for the boosts in the curve.
 *
 * Equal and opposite to the largest boost, which is what AutoEq publishes and
 * what stops a +6 dB band clipping the output. Cuts need none, so a curve that
 * only cuts gets a preamp of 0 rather than a pointless attenuation.
 */
export const preampFor = (eq: IEqSettings): number => {
  const peak = eq.bands
    .filter((band) => band.enabled)
    .reduce((highest, band) => Math.max(highest, band.gainDb), 0);
  return peak > 0 ? -peak : 0;
};

/** `ON PK Fc 1200 Hz Gain -2.1 dB Q 1.41`, in one expression. */
const FILTER_LINE =
  /^\s*Filter\s+\d+\s*:\s*(ON|OFF)\s+([A-Z]+)\s+Fc\s+([\d.]+)\s*Hz(?:\s+Gain\s+(-?[\d.]+)\s*dB)?(?:\s+Q\s+([\d.]+))?/i;

export interface IApoImport {
  bands: IEqBandSettings[];
  /** What the file asked for, for the caller to apply or ignore. */
  preampDb: number;
  /** Lines that were not filters or a preamp. Empty on a clean file. */
  skipped: number;
}

/**
 * Read a ParametricEQ file into bands.
 *
 * Lenient on purpose. These files are pasted, hand-edited and generated by a
 * dozen tools: some write `Q 0.7`, some `Q 0.70`, some omit Q on a shelf
 * entirely, and AutoEq's own exports put a `Preamp:` line first. Anything
 * unrecognised is counted and skipped rather than failing the whole import,
 * because one odd line in a forty-line file should not cost the other
 * thirty-nine.
 *
 * Never returns more than `EQ_BAND_COUNT` bands — this EQ has a fixed rack, so
 * a longer file is truncated and the caller is told how many were dropped.
 */
export const fromApoText = (text: string): IApoImport => {
  const bands: IEqBandSettings[] = [];
  let preampDb = 0;
  let skipped = 0;

  text.split(/\r\n|[\r\n]/).forEach((raw) => {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) {
      return;
    }
    const preamp = /^Preamp\s*:\s*(-?[\d.]+)\s*dB/i.exec(line);
    if (preamp) {
      preampDb = Number(preamp[1]);
      return;
    }
    const match = FILTER_LINE.exec(line);
    if (!match) {
      skipped += 1;
      return;
    }
    if (bands.length >= EQ_BAND_COUNT) {
      skipped += 1;
      return;
    }
    const [, state, type, frequency, gain, quality] = match;
    bands.push({
      enabled: state.toUpperCase() === 'ON',
      type: type.toUpperCase(),
      frequency: Number(frequency),
      // A missing Gain is 0, not a failure: that is what the grammar means for
      // a notch or a pass, and some tools omit it on shelves too.
      gainDb: gain === undefined ? 0 : Number(gain),
      // A missing Q is the Butterworth default every one of these tools uses
      // when it leaves the token out.
      quality: quality === undefined ? 0.707 : Number(quality),
    });
  });

  return { bands, preampDb, skipped };
};
