/*
<FluidEQ: System-wide parametric audio equalizer interface>
Copyright (C) <2026>  <Ivan Carmenates Garcia>
SPDX-License-Identifier: GPL-3.0-or-later
*/

import { NO_GAIN_FILTER_TYPES } from '../constants';
import { EQ_MAX_BAND_COUNT, IEqBandSettings, IEqSettings } from './chain';

/**
 * Equalizer APO's ParametricEQ text, read and written.
 *
 * The format AutoEq, oratory1990, Squiglink and every headphone correction
 * database publishes in, which is the whole point: a curve someone downloads
 * for their headphones should load here, and a curve made here should paste
 * into `config.txt` and behave identically.
 *
 *     Filter 1: ON LSC Fc 105 Hz Gain 5.5 dB Q 0.70
 *     Filter 2: ON PK Fc 1200 Hz Gain -2.1 dB Q 1.41
 *     Filter 3: ON HPQ Fc 30 Hz Q 0.71
 *
 * Band pass, notch, low pass and high pass carry NO Gain token — APO's grammar
 * has no gain for those forms and a line that includes one is rejected
 * outright, which `apoRender.ts` already learned the hard way. Both directions
 * here honour that.
 */

/** Trailing zeros off: `3.5` rather than `3.50`, `4` rather than `4.00`. */
const round = (value: number) => Math.round(value * 100) / 100;

export const toApoText = (eq: IEqSettings): string => {
  const lines = eq.bands
    .filter((band) => band.enabled)
    .map((band, index) => {
      const head = `Filter ${index + 1}: ON ${band.type} Fc ${round(
        band.frequency,
      )} Hz`;
      const q = `Q ${round(band.quality)}`;
      return NO_GAIN_FILTER_TYPES.includes(band.type as never)
        ? `${head} ${q}`
        : `${head} Gain ${round(band.gainDb)} dB ${q}`;
    });
  return lines.join('\n');
};

/**
 * `ON PK Fc 1200 Hz Gain -2.1 dB Q 1.41`, numbered or not.
 *
 * The index is OPTIONAL, and that is not a nicety. AutoEq writes `Filter 1:`;
 * Squiglink writes a bare `Filter:` on every line. Requiring the number matched
 * zero of ten lines in a real Squiglink export — the import reported an empty
 * file and looked like it had simply failed.
 */
const FILTER_LINE =
  /^\s*Filter\s*(?:\d+\s*)?:\s*(ON|OFF)\s+([A-Za-z]+)\s+Fc\s+([\d.]+)\s*Hz(?:\s+Gain\s+(-?[\d.]+)\s*dB)?(?:\s+Q\s+([\d.]+))?/i;

/**
 * What the publishers write, against what this equaliser calls it.
 *
 * The same filter has two spellings in the wild: APO's own config uses `LSC`
 * and `HSC`, while Squiglink, AutoEq and oratory1990 all publish `LS` and `HS`.
 * A file using the short form used to import as an unknown type and be dropped
 * on the floor by `clampEqBand`, which is a silent way to lose the two bands
 * that shape the ends of the curve.
 */
const TYPE_ALIASES: Record<string, string> = {
  LS: 'LSC',
  HS: 'HSC',
  PEQ: 'PK',
  LP: 'LPQ',
  HP: 'HPQ',
  NOTCH: 'NO',
};

const KNOWN_TYPES = ['PK', 'NO', 'LSC', 'HSC', 'LPQ', 'HPQ', 'BP'];

export interface IApoImport {
  bands: IEqBandSettings[];
  /** Lines that were not filters or recognized metadata. */
  skipped: number;
}

/**
 * Read a ParametricEQ file into bands.
 *
 * Lenient on purpose. These files are pasted, hand-edited and generated by a
 * dozen tools: some write `Q 0.7`, some `Q 0.70`, some omit Q on a shelf
 * entirely. Publisher level metadata is deliberately ignored: level belongs
 * to the source Normalizer and final Master, never to the EQ curve. Anything
 * unrecognised is counted and skipped rather than failing the whole import,
 * because one odd line in a forty-line file should not cost the other
 * thirty-nine.
 *
 * The rack takes the file's own band count rather than the file being cut to
 * the rack's. Truncating a published curve to fifteen filters threw away the
 * ones the author put at the top and produced a curve that was not the one on
 * the page. `EQ_MAX_BAND_COUNT` is the only ceiling, and it is a CPU budget
 * rather than a format limit.
 */
export const fromApoText = (text: string): IApoImport => {
  const bands: IEqBandSettings[] = [];
  let skipped = 0;

  text.split(/\r\n|[\r\n]/).forEach((raw) => {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) {
      return;
    }
    if (/^Preamp\s*:/i.test(line)) {
      return;
    }
    const match = FILTER_LINE.exec(line);
    if (!match) {
      skipped += 1;
      return;
    }
    if (bands.length >= EQ_MAX_BAND_COUNT) {
      skipped += 1;
      return;
    }
    const [, state, rawType, frequency, gain, quality] = match;
    const spelled = rawType.toUpperCase();
    const type = TYPE_ALIASES[spelled] ?? spelled;
    // A shape this equaliser has no coefficients for — APO's `AP`, or a
    // `None` placeholder. Counted rather than coerced: turning an unknown
    // filter into a bell invents a curve the file did not describe.
    if (!KNOWN_TYPES.includes(type)) {
      skipped += 1;
      return;
    }
    bands.push({
      enabled: state.toUpperCase() === 'ON',
      // A published correction is a static curve by construction: the format
      // has no way to say otherwise, so inventing a threshold would be reading
      // something into the file that is not in it.
      dynamic: false,
      thresholdDb: -24,
      type,
      frequency: Number(frequency),
      // A missing Gain is 0, not a failure: that is what the grammar means for
      // a notch or a pass, and some tools omit it on shelves too.
      gainDb: gain === undefined ? 0 : Number(gain),
      // A missing Q is the Butterworth default every one of these tools uses
      // when it leaves the token out.
      quality: quality === undefined ? 0.707 : Number(quality),
    });
  });

  return { bands, skipped };
};
