/*
<FluidEQ: System-wide parametric audio equalizer interface>
Copyright (C) <2026>  <Ivan Carmenates Garcia>
SPDX-License-Identifier: GPL-3.0-or-later
*/

/**
 * The featured rooms as the text of `room_profiles_fixture.h`.
 *
 * One function for the two that need it: the script that writes the header
 * and the test that holds the header to the table. Two copies of this layout
 * would agree until a field was added to one of them.
 */
import { ROOM_FEATURED_LIST, TRoomShape } from './roomPresets';

/** The header's column order; `settings_of` in the engine test reads it. */
const valuesOf = (shape: TRoomShape): number[] => [
  shape.sizeM,
  shape.walls,
  shape.distanceM,
  shape.centreDb,
  shape.subDb,
  ...shape.angles,
  ...shape.levels,
  ...shape.distances,
  ...shape.mutes.map(Number),
  Number(shape.bassManagement),
  shape.crossoverHz,
  Number(shape.musicUpmix),
  shape.upmixAmount,
  shape.rendererVersion,
  shape.earlyReflectionDb,
  shape.ambienceMix,
  shape.ambienceDecayS,
  shape.ambienceDampingHz,
  Number(shape.preservePosition),
];

export const ROOM_PROFILE_FIXTURE_VALUES = 44;

export const roomProfilesFixture = (): string => {
  const rows = ROOM_FEATURED_LIST.map((preset) => {
    const values = valuesOf(preset.shape);
    if (values.length !== ROOM_PROFILE_FIXTURE_VALUES) {
      throw new Error(
        `room profiles fixture: ${preset.id} has ${values.length} values`,
      );
    }
    return `  {"${preset.id}", {${values.join(', ')}}},`;
  });
  return [
    '// Generated by .erb/scripts/generate-room-profiles-fixture.ts; do not edit.',
    '#pragma once',
    '// sizeM, walls, distanceM, centreDb, subDb, angles x7, levels x7, distances x7,',
    '// mutes x8, bassManagement, crossoverHz, musicUpmix, upmixAmount,',
    '// rendererVersion, earlyReflectionDb, ambienceMix, ambienceDecayS,',
    '// ambienceDampingHz, preservePosition.',
    'struct RoomProfileFixture {',
    '  const char* id;',
    `  double values[${ROOM_PROFILE_FIXTURE_VALUES}];`,
    '};',
    'inline constexpr RoomProfileFixture kRoomProfiles[] = {',
    ...rows,
    '};',
    '',
  ].join('\n');
};
