/*
<FluidEQ: System-wide parametric audio equalizer interface>
Copyright (C) <2026>  <Ivan Carmenates Garcia>
SPDX-License-Identifier: GPL-3.0-or-later
*/

/**
 * The featured rooms as the text of `room_profiles_fixture.h`.
 *
 * One function for the two that need it: the script that writes the header
 * and the test that holds the header to the table. Two copies of this layout
 * would agree until a field was added to one of them.
 */
import { FilterTypeEnum } from '../constants';
import { DSP_PRESET_RECIPES } from './presetRecipes';
import { ROOM_FEATURED_LIST, TRoomShape } from './roomPresets';
import { ROOM_TONE_SETS, roomToneSetOf } from './roomTone';

/** The header's column order; `settings_of` in the engine test reads it. */
const valuesOf = (shape: TRoomShape): number[] => [
  shape.sizeM,
  shape.walls,
  shape.distanceM,
  shape.centreDb,
  shape.subDb,
  ...shape.angles,
  ...shape.levels,
  ...shape.distances,
  ...shape.mutes.map(Number),
  Number(shape.bassManagement),
  shape.crossoverHz,
  Number(shape.musicUpmix),
  shape.upmixAmount,
  shape.rendererVersion,
  shape.earlyReflectionDb,
  shape.ambienceMix,
  shape.ambienceDecayS,
  shape.ambienceDampingHz,
  Number(shape.preservePosition),
];

export const ROOM_PROFILE_FIXTURE_VALUES = 44;

/** `FeqFilterType`, by the app's name for it. */
const NATIVE_FILTER: Record<string, number | undefined> = {
  [FilterTypeEnum.PK]: 0,
  [FilterTypeEnum.LSC]: 2,
  [FilterTypeEnum.HSC]: 3,
};

/** The rooms the rack's Room copies stand in, each with its tone bands. */
const toneRows = (): string[] =>
  Array.from(
    new Set(DSP_PRESET_RECIPES.flatMap((recipe) => recipe.room ?? [])),
  ).map((room) => {
    const bands = ROOM_TONE_SETS[roomToneSetOf(room)].map((band) => {
      const type = NATIVE_FILTER[band.type];
      if (type === undefined) {
        throw new Error(`room tone fixture: no native filter for ${band.type}`);
      }
      return `{${type}, ${band.frequency}, ${band.gainDb}, ${band.quality}}`;
    });
    return `  {"${room}", {${bands.join(', ')}}},`;
  });

export const roomProfilesFixture = (): string => {
  const rows = ROOM_FEATURED_LIST.map((preset) => {
    const values = valuesOf(preset.shape);
    if (values.length !== ROOM_PROFILE_FIXTURE_VALUES) {
      throw new Error(
        `room profiles fixture: ${preset.id} has ${values.length} values`,
      );
    }
    return `  {"${preset.id}", {${values.join(', ')}}},`;
  });
  return [
    '// Generated by .erb/scripts/generate-room-profiles-fixture.ts; do not edit.',
    '#pragma once',
    '// sizeM, walls, distanceM, centreDb, subDb, angles x7, levels x7, distances x7,',
    '// mutes x8, bassManagement, crossoverHz, musicUpmix, upmixAmount,',
    '// rendererVersion, earlyReflectionDb, ambienceMix, ambienceDecayS,',
    '// ambienceDampingHz, preservePosition.',
    'struct RoomProfileFixture {',
    '  const char* id;',
    `  double values[${ROOM_PROFILE_FIXTURE_VALUES}];`,
    '};',
    'inline constexpr RoomProfileFixture kRoomProfiles[] = {',
    ...rows,
    '};',
    '// The EQ bands a Room copy of a chain adds (`roomTone.ts`), by the room',
    '// the copy stands in: FeqFilterType, Hz, dB, Q.',
    'struct RoomToneBandFixture {',
    '  int type;',
    '  double hz;',
    '  double gain_db;',
    '  double q;',
    '};',
    'struct RoomToneFixture {',
    '  const char* room;',
    '  RoomToneBandFixture bands[5];',
    '};',
    'inline constexpr RoomToneFixture kRoomTones[] = {',
    ...toneRows(),
    '};',
    '',
  ].join('\n');
};
