/*
<FluidEQ: System-wide parametric audio equalizer interface>
Copyright (C) <2026>  <Ivan Carmenates Garcia>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 or later.
*/

import path from 'path';
import { createHash } from 'crypto';
import log from 'electron-log';
import { getEqMode, getCurveEqMode } from '../common/eqMode';
import { normalizeBandDesign } from '../common/bandDesigns';
import {
  ICustomFxSettings,
  IDeviceProfileAssignment,
  IDeviceProfileSettings,
  IEqCuts,
  IPresetV2,
  IState,
  IVoicingSettings,
  TApoFeature,
  apoFeatureFileWord,
  getDefaultState,
} from '../common/constants';
import { EQ_CUTS_FILENAME, eqCutsFileText, hasEqCut } from '../common/eqCuts';
import { toTone } from '../common/tone';
import { dspVoicingPresetId } from '../common/dsp/presetVoicing';
import {
  addFileToPath,
  FLUIDEQ_CONFIG_FILENAME,
  fetchPreset,
  IApoChainFiles,
  readPresetText,
  savePreset,
  stateToApoFiles,
} from './flush';
import { parseCustomFx } from '../common/customFx';
import { layerGroupOf, MATCHED_DESIGN_DIRECTIVE } from '../common/filterDesign';

import readTextCached from './cachedRead';
import writeConvolutionWav from './convolution';
import { hydrateConvolutionAnalysis } from './convolutionAnalysis';

export interface IActiveStateOverride {
  deviceId?: string;
  /**
   * What Windows calls this output, for the comment above its block.
   *
   * Every other block is headed `<output> -> <profile>`, and that comment is
   * the only thing in the config that names an output in words — the `Device:`
   * line is a GUID and the file names are a digest of one. A session override
   * had no name to put there, so the one output somebody is listening through
   * was the one whose files could not say what they were for.
   */
  deviceName?: string;
  devicePattern: string;
  state: IState;
}

/**
 * What the session has measured, and which output it was measured on.
 *
 * THE PREAMP IS RENDERED FROM THE PROFILE, AND THIS IS NOT IN THE PROFILE.
 *
 * That sentence is the whole reason this type exists. Auto normalize measures
 * the music in the renderer and reports it to the live state, where the display
 * reads it — but the config is built from the saved preset, and a preset cannot
 * carry a measurement (it is evidence about this session, and persisting it
 * would apply last night's music to this morning's record). So the two answers
 * were computed from two different states: the window showed the adaptive
 * number and the `Preamp:` line kept the worst case, for ever, on every output
 * with a profile attached — which is every output. The level never moved while
 * the readout said it had.
 *
 * Carrying the evidence alongside the profiles closes that, and carrying the
 * device with it is what keeps it honest: the loopback hears one endpoint, so
 * the measurement is applied to that endpoint's chain and to no other.
 */
export interface ISessionHeadroom {
  /** The output this was measured on. Evidence for one is not evidence for another. */
  deviceId?: string;
  programme?: IState['smartHeadroomProgramme'];
  trimDb?: number;
}

/**
 * Whether this name may be written into a `Convolution:` line.
 *
 * `path.basename` splits on separators and nothing else, so the old pair of
 * checks accepted a name containing a newline — and A NEWLINE IN AN APO CONFIG
 * FILE ENDS THE COMMAND. A name of `ir.wav`, a carriage return, and a `Plugin:`
 * line would have been written out as two commands, the second of which makes
 * Equalizer APO load a DLL into the Windows audio pipeline.
 *
 * Reachable because a preset read from disk does not pass through
 * `normalizeConvolution` and the preset schema does not constrain this field at
 * all, so an imported profile is the delivery mechanism. Found in review rather
 * than the other way round.
 *
 * Every control character rather than the two that end a line: what the config
 * parser does with a NUL or an escape is not this file's to reason about, and
 * none of them belong in a filename anybody meant to write.
 */
const isSafeConvolutionFileName = (fileName: string) =>
  fileName === path.basename(fileName) &&
  !fileName.includes('..') &&
  // eslint-disable-next-line no-control-regex -- the characters are the point
  !/[\u0000-\u001f\u007f]/.test(fileName);

export const CRLF = '\r\n';

/**
 * The root both engines read as "nothing to do": comments only, no `Device:`
 * block and no `Include:`. Written with the power switch off, into the engine
 * being left at a switch, and into the engine in use when FluidEQ quits — at
 * the next launch the startup read finds no block in it to adopt, so the saved
 * EQ is what gets written back.
 */
export const DISABLED_ROOT_TEXT = [
  '# Generated by FluidEQ. Changes are overwritten automatically.',
  '# FluidEQ engine disabled; no Equalizer APO rules are active.',
].join(CRLF);

/**
 * A short, filename-safe stand-in for an endpoint.
 *
 * Windows endpoint ids are long and full of characters a filename should not
 * carry, and they are the only thing that identifies an output uniquely. The
 * digest is stable across runs, which is what makes a device's files findable
 * again rather than accumulating one set per launch.
 */
const deviceSlug = (deviceKey: string) =>
  createHash('sha1').update(deviceKey).digest('hex').slice(0, 12);

const getConvolutionFileName = (deviceId: string) =>
  `fluideq-convolution-${deviceSlug(deviceId)}.wav`;

const deviceFileName = (slug: string) => `fluideq-device-${slug}.txt`;

const featureFileName = (slug: string, feature: TApoFeature) =>
  `fluideq-${slug}-${apoFeatureFileWord(feature)}.txt`;

/**
 * The one file in a device's chain that FluidEQ does not write.
 *
 * Created empty when an output first gets a chain and never touched again, so
 * whatever goes in it survives every flush. Every other file here is generated
 * from the profile and rewritten the moment anything changes, which makes them
 * all the wrong place to put anything by hand — a hand edit to one is not
 * refused, it simply disappears at the next slider move.
 *
 * This is where an Equalizer APO command FluidEQ has no interface for belongs:
 * a `Plugin:` line for a VST, a `Copy:` for channel routing, a `Delay:`.
 */
export const customFileName = (slug: string) => `fluideq-${slug}-custom.txt`;

/**
 * The custom file belonging to one output, by its endpoint id.
 *
 * Exported because exporting a chain has to carry this file literally: it is
 * the one part of an output's chain that is not generated from the profile, so
 * it is the one part that cannot be rebuilt at the other end. The slug is a
 * digest and the name is assembled from it in two places here, neither of which
 * anything outside this file should be reproducing by hand.
 */
export const getCustomFileNameForDevice = (deviceId: string) =>
  customFileName(deviceSlug(deviceId));

/** The text of an output's user-owned custom file, if it has one. */
const readCustomText = (
  configDirPath: string | undefined,
  deviceId: string,
): string | undefined => {
  if (!configDirPath || !deviceId) {
    return undefined;
  }
  try {
    return readTextCached(
      addFileToPath(configDirPath, getCustomFileNameForDevice(deviceId)),
    );
  } catch {
    return undefined;
  }
};

/** The measurable EQ portion of that text. */
const parseCustomText = (
  deviceId: string,
  text: string | undefined,
): ICustomFxSettings | undefined => {
  if (text === undefined) {
    return undefined;
  }
  try {
    return parseCustomFx(getCustomFileNameForDevice(deviceId), text);
  } catch {
    return undefined;
  }
};

/** Read the measurable EQ portion of an output's user-owned custom file. */
const readCustomFx = (
  configDirPath: string | undefined,
  deviceId: string,
): ICustomFxSettings | undefined =>
  parseCustomText(deviceId, readCustomText(configDirPath, deviceId));

/** What a custom file says before anybody has put anything in it. */
export const CUSTOM_FILE_TEMPLATE = [
  '# Yours. FluidEQ creates this file once and never writes it again, so',
  '# anything here survives every change made in the app.',
  '#',
  '# Applied last, after the generated chain and after its preamp. Equalizer',
  '# APO commands go here — Plugin:, Copy:, Delay: and the rest.',
  '',
];

const presetForDeviceChain = (
  preset: IPresetV2,
  convolutionFileName?: string,
  customFx?: ICustomFxSettings,
  headroom?: ISessionHeadroom,
) => {
  const presetState = {
    isEnabled: true,
    isGraphViewOn: false,
    isCaseSensitiveFs: false,
    ...preset,
    // After the spread, not before: a preset that carries the key explicitly
    // undefined would otherwise overwrite the default with nothing. Absent
    // means automatic, which every profile written before the flag existed was.
    isAutoPreAmpOn: preset.isAutoPreAmpOn ?? true,
    customFx,
    // The one thing the chain needs that the profile is not allowed to hold.
    // Absent for every output except the one being listened through, where its
    // absence is exactly the cold start the preamp already knows how to answer.
    smartHeadroomProgramme: headroom?.programme,
    smartHeadroomTrimDb: headroom?.trimDb,
  };

  return stateToApoFiles(presetState, convolutionFileName);
};

/** One output's share of the config: its root block and the files it includes. */
interface IDeviceFiles {
  /** The `Device:` / `Channel:` / `Include:` trio that goes in fluideq.txt. */
  block: string;
  /** Filename to contents, feature files before the device file naming them. */
  files: Array<[string, string]>;
}

/**
 * Lay one device's chain out as files.
 *
 * The root only ever names the device file, and the device file only ever names
 * its features. Nothing in this shape says which output is current, which is
 * the point: APO's own `Device:` guard picks the matching block at playback
 * time, so switching Windows outputs needs no config write at all.
 *
 * The guard reaches into the included files too, which is what makes a device
 * file safe to write without repeating the `Device:` line inside it.
 * `DeviceFilterFactory` keeps `deviceMatches` across a nested file load — there
 * is no per-file reset, only a `startOfConfiguration` one — and while it is
 * false every command is blanked, the `Include:` line included. So another
 * output's files are not merely filtered out at playback; they are never opened.
 */
const chainToFiles = (
  chain: IApoChainFiles,
  subject: string,
  devicePattern: string,
  deviceKey: string,
  includesCuts: boolean,
): IDeviceFiles => {
  const slug = deviceSlug(deviceKey);
  const files: Array<[string, string]> = chain.features.map(
    ({ feature, lines }) => [
      featureFileName(slug, feature),
      [
        `# ${feature}: ${subject}`,
        // Which row of the EQ mode menu the engine plays this file by: Your
        // EQ's for everything but a headphone correction (`layerGroupOf`).
        layerGroupOf(feature) === 'eq'
          ? '# FluidEQEqLayer: ON'
          : '# FluidEQCurveLayer: ON',
        MATCHED_DESIGN_DIRECTIVE,
        ...lines,
      ].join(CRLF),
    ],
  );

  files.push([
    deviceFileName(slug),
    [
      `# ${subject}`,
      // Before the features, because APO applies an impulse response ahead of
      // the filters and reads the file top to bottom.
      ...(chain.convolution ? [chain.convolution] : []),
      ...chain.features.map(
        ({ feature }) => `Include: ${featureFileName(slug, feature)}`,
      ),
      // After the includes: it is the peak of everything they add up to, so it
      // cannot be decided until they have all had their say.
      chain.preAmp,
      ...(chain.engineDirectives ?? []),
      // The cuts, after the preamp because they are not part of what it is
      // sized for: they only take away (`eqCuts.ts`). One file for every
      // output, so a cut switched on or off is one write. It is not a layer
      // and not in this device file, so reading the config back never takes
      // its lines for bands (`readApoDeviceChain`).
      ...(includesCuts ? [`Include: ${EQ_CUTS_FILENAME}`] : []),
      // And the user's own file after even that.
      //
      // Everything above is generated and rewritten on the next edit, so it is
      // no place to put anything by hand. This one is never generated: FluidEQ
      // creates it empty and then leaves it alone forever, which makes it the
      // only line in the chain somebody can own.
      //
      // Last on purpose, and after the preamp rather than before it. FluidEQ
      // cannot know what is in here, so it cannot reserve headroom for it —
      // running it after the reserve keeps the arithmetic above honest and
      // makes the ownership plain: this is the generated chain, and then this
      // is yours.
      ...(chain.custom === false ? [] : [`Include: ${customFileName(slug)}`]),
      ...(chain.customEqCompensation ?? []),
    ].join(CRLF),
  ]);

  return {
    block: [
      `# ${subject}`,
      `Device: ${devicePattern}`,
      'Channel: all',
      `Include: ${deviceFileName(slug)}`,
    ].join(CRLF),
    files,
  };
};

/**
 * Every file the Equalizer APO config is made of, keyed by filename.
 *
 * Iteration order is write order: a feature file always comes before the device
 * file whose `Include:` names it, and `fluideq.txt` is last of all. At no point
 * does a file on disk point at one that is not there yet.
 */
export type TApoConfigFiles = Map<string, string>;

/**
 * Where to find one output's profiles.
 *
 * Passed in rather than computed here, because the answer is a directory this
 * module has no business knowing how to build — it needs the app's user-data
 * path and the hash that names an output's folder, and both belong to main.
 *
 * A function rather than a directory because profiles are per output: there is
 * no single folder these functions can read, and every assignment carries the
 * device id that picks one. Handing over a flat path is what made two outputs
 * share a namespace in the first place.
 */
export type TPresetDirForDevice = (deviceId: string) => string;

/**
 * One attached output's share of the config, rendered from its profile, and
 * whether it can be kept: a profile with an impulse writes its WAV and
 * migrates its analysis as it renders, so it is rendered every time, as it
 * always was.
 */
const renderAssignedDevice = (
  assignment: IDeviceProfileAssignment,
  dir: string,
  configDirPath: string | undefined,
  customText: string | undefined,
  headroom: ISessionHeadroom | undefined,
  includesCuts: boolean,
): { device?: IDeviceFiles; keepable: boolean } => {
  const preset = fetchPreset(assignment.presetName, dir);
  if (configDirPath && preset.convolution?.fileName) {
    try {
      const hydrated = hydrateConvolutionAnalysis(
        preset.convolution,
        configDirPath,
      );
      if (hydrated !== preset.convolution) {
        preset.convolution = hydrated;
        savePreset(
          assignment.presetName,
          preset,
          dir,
          'convolution-analysis-migration',
        );
      }
    } catch {
      // Keep the profile usable if a legacy WAV cannot be analyzed. APO
      // will report an unreadable convolution independently.
    }
  }
  let convolutionFileName: string | undefined;
  if (configDirPath && preset.convolution) {
    convolutionFileName = getConvolutionFileName(assignment.deviceId);
    if (
      preset.convolution.fileName &&
      isSafeConvolutionFileName(preset.convolution.fileName)
    ) {
      convolutionFileName = preset.convolution.fileName;
    }
  }
  if (configDirPath && preset.convolution && convolutionFileName) {
    if (!preset.convolution.fileName) {
      writeConvolutionWav(
        addFileToPath(configDirPath, convolutionFileName),
        preset.convolution.filters,
      );
    }
  }
  const chain = presetForDeviceChain(
    preset,
    convolutionFileName,
    parseCustomText(assignment.deviceId, customText),
    headroom,
  );
  return {
    device: chain
      ? chainToFiles(
          chain,
          `${assignment.deviceName} -> ${assignment.presetName}`,
          assignment.deviceGuid || assignment.deviceName,
          assignment.deviceId,
          includesCuts,
        )
      : undefined,
    keepable: !preset.convolution,
  };
};

/** Everything an attached output's rendered chain is made from. */
interface IRenderedDeviceInputs {
  presetDir: string;
  presetText: string;
  customText: string | undefined;
  headroom: string;
  configDirPath: string | undefined;
  includesCuts: boolean;
  deviceName: string;
  devicePattern: string;
  presetName: string;
}

/**
 * Each attached output's last render, by output, beside what it was made from.
 *
 * Every edit rendered every attached output again — read its profile, parse
 * it, validate it twice, build its layers and size its preamp — although an
 * edit changes one output, and the others' profiles and custom files come
 * back from `readTextCached` as the very strings they were last time. When
 * every input is identical the render would be too, so it is taken as it was.
 */
const renderedDevices = new Map<
  string,
  { inputs: IRenderedDeviceInputs; device: IDeviceFiles | undefined }
>();

const sameRenderInputs = (
  left: IRenderedDeviceInputs,
  right: IRenderedDeviceInputs,
) =>
  (Object.keys(left) as Array<keyof IRenderedDeviceInputs>).every(
    (key) => left[key] === right[key],
  );

const readPresetTextIfAny = (presetName: string, dir: string) => {
  try {
    return readPresetText(presetName, dir);
  } catch {
    // Unreadable is not remembered: `fetchPreset` reads it again and says why.
    return undefined;
  }
};

export const deviceProfilesToFiles = (
  settings: IDeviceProfileSettings,
  presetDirForDevice: TPresetDirForDevice,
  configDirPath?: string,
  activeOverride?: IActiveStateOverride,
  isEnabled = true,
  sessionHeadroom: ISessionHeadroom | undefined = undefined,
  cuts: IEqCuts | undefined = undefined,
): TApoConfigFiles => {
  const files: TApoConfigFiles = new Map();

  if (!isEnabled) {
    files.set(FLUIDEQ_CONFIG_FILENAME, DISABLED_ROOT_TEXT);
    return files;
  }

  // First, because every device file below includes it.
  const includesCuts = hasEqCut(cuts);
  if (includesCuts && cuts) {
    files.set(EQ_CUTS_FILENAME, eqCutsFileText(cuts));
  }

  const blocks: string[] = [];
  const addDeviceFiles = (device: IDeviceFiles | undefined) => {
    if (!device) {
      return;
    }
    device.files.forEach(([name, contents]) => files.set(name, contents));
    blocks.push(device.block);
  };
  const addDevice = (
    chain: IApoChainFiles | undefined,
    subject: string,
    devicePattern: string,
    deviceKey: string,
  ) =>
    addDeviceFiles(
      chain
        ? chainToFiles(chain, subject, devicePattern, deviceKey, includesCuts)
        : undefined,
    );

  // Equalizer APO accumulates: every block whose `Device:` line matches the
  // output contributes its commands, and a later block does NOT reset an
  // earlier one. So if the device the user is listening on also has a preset
  // assigned, emitting both blocks stacks the preset's filters underneath the
  // live session instead of replacing them — pressing Clear EQ would leave the
  // preset fully audible. The session override wins, so its device drops out
  // of the assignment list entirely.
  const isOverriddenDevice = (assignment: IDeviceProfileAssignment) => {
    if (!activeOverride) {
      return false;
    }
    const pattern = assignment.deviceGuid || assignment.deviceName;
    return (
      (!!activeOverride.deviceId &&
        activeOverride.deviceId === assignment.deviceId) ||
      activeOverride.devicePattern === pattern
    );
  };

  Object.values(settings.assignments)
    .filter((assignment) => !isOverriddenDevice(assignment))
    .forEach((assignment) => {
      try {
        const dir = presetDirForDevice(assignment.deviceId);
        // Only the output it was measured on. Handing another endpoint this
        // evidence would reserve its headroom from music that never went
        // through it.
        const headroom =
          sessionHeadroom?.deviceId &&
          sessionHeadroom.deviceId === assignment.deviceId
            ? sessionHeadroom
            : undefined;
        const customText = readCustomText(configDirPath, assignment.deviceId);
        const presetText = readPresetTextIfAny(assignment.presetName, dir);
        const inputs: IRenderedDeviceInputs | undefined =
          presetText === undefined
            ? undefined
            : {
                presetDir: dir,
                presetText,
                customText,
                headroom: headroom
                  ? JSON.stringify([headroom.programme, headroom.trimDb])
                  : '',
                configDirPath,
                includesCuts,
                deviceName: assignment.deviceName,
                devicePattern: assignment.deviceGuid || assignment.deviceName,
                presetName: assignment.presetName,
              };
        const remembered = renderedDevices.get(assignment.deviceId);
        if (
          inputs &&
          remembered &&
          sameRenderInputs(remembered.inputs, inputs)
        ) {
          addDeviceFiles(remembered.device);
          return;
        }
        renderedDevices.delete(assignment.deviceId);
        const rendered = renderAssignedDevice(
          assignment,
          dir,
          configDirPath,
          customText,
          headroom,
          includesCuts,
        );
        if (inputs && rendered.keepable) {
          renderedDevices.set(assignment.deviceId, {
            inputs,
            device: rendered.device,
          });
        }
        addDeviceFiles(rendered.device);
      } catch (e) {
        // A profile we cannot read is one this device simply does not get —
        // the config is still written for every other output rather than one
        // bad file taking the whole chain down.
        //
        // SAID OUT LOUD, WHICH IT WAS NOT. Dropping an output here means it
        // stops being equalised entirely, and the bare catch made that the
        // quietest possible failure: no line in the log, no error in the
        // window, just an endpoint missing from a config nobody reads. That is
        // what hid the rename bug — a rename repointed four other outputs at a
        // file that was not in their folder, and all four vanished from the
        // chain without a word until something later tried to load one by name
        // and blamed the preset directory.
        log.error(
          `Output "${assignment.deviceName}" was left out of the config: its profile "${assignment.presetName}" could not be read`,
        );
        log.error(e);
      }
    });

  // An output that is no longer attached leaves no render behind.
  const attached = new Set(
    Object.values(settings.assignments).map(({ deviceId }) => deviceId),
  );
  renderedDevices.forEach((_render, deviceId) => {
    if (!attached.has(deviceId)) {
      renderedDevices.delete(deviceId);
    }
  });

  if (activeOverride) {
    let activeState = activeOverride.state;
    if (configDirPath && activeState.convolution?.fileName) {
      try {
        const hydrated = hydrateConvolutionAnalysis(
          activeState.convolution,
          configDirPath,
        );
        if (hydrated !== activeState.convolution) {
          activeState = { ...activeState, convolution: hydrated };
          activeOverride.state.convolution = hydrated;
        }
      } catch {
        // Same legacy fallback as assigned profiles above.
      }
    }
    let activeConvolutionFileName: string | undefined;
    if (activeState.convolution) {
      if (
        activeState.convolution.fileName &&
        isSafeConvolutionFileName(activeState.convolution.fileName)
      ) {
        activeConvolutionFileName = activeState.convolution.fileName;
      } else if (configDirPath && activeOverride.deviceId) {
        activeConvolutionFileName = getConvolutionFileName(
          activeOverride.deviceId,
        );
        writeConvolutionWav(
          addFileToPath(configDirPath, activeConvolutionFileName),
          activeState.convolution.filters,
        );
      }
    }

    const activeCustomFx =
      activeState.customFx ??
      readCustomFx(configDirPath, activeOverride.deviceId ?? '');
    addDevice(
      stateToApoFiles(
        { ...activeState, customFx: activeCustomFx },
        activeConvolutionFileName,
      ),
      // In the same `<output> -> <what it is>` shape every other block carries,
      // so the config view splits it the same way and the device file's first
      // line names the output rather than only the mechanism. Without a name to
      // put there it stays what it was — a caller that cannot say which output
      // this is must not be made to invent one.
      activeOverride.deviceName
        ? `${activeOverride.deviceName} -> Active FluidEQ session`
        : 'Active FluidEQ session override',
      activeOverride.devicePattern,
      activeOverride.deviceId || activeOverride.devicePattern,
    );
  }

  // Nothing includes the cuts without an output to carry them.
  if (blocks.length === 0) {
    files.delete(EQ_CUTS_FILENAME);
  }

  // Last, so the file that names every other one is written after them.
  files.set(
    FLUIDEQ_CONFIG_FILENAME,
    [
      '# Generated by FluidEQ. Changes are overwritten automatically.',
      [
        '# Neutral fallback for every output without an attached profile.',
        'Device: all',
        'Channel: all',
      ].join(CRLF),
      ...blocks,
    ].join(`${CRLF}${CRLF}`),
  );

  return files;
};

/**
 * The full EQ state for a device, with every optional field present.
 *
 * Spreading a preset over the defaults is not enough, because callers apply the
 * result with Object.assign: a key the preset does not have is simply absent
 * from the object, so the assign leaves the PREVIOUS device's value in place.
 * That is how one device's convolution, voicing, driver correction, Smart EQ
 * correction or preamp followed the user onto every other output — and, once
 * edits started auto-saving, got written into those devices' profiles for good.
 *
 * Every optional field is therefore listed explicitly, undefined included, so
 * assigning this over the live state clears what the new device does not have.
 */
/**
 * A PRESET'S CURVE IS THE MACHINE'S CHOICE, NOT THE OUTPUT'S.
 *
 * The rack is one choice for the whole machine, and a preset is the rack and
 * its curve together — so the curve cannot be per output, or the two disagree
 * the moment an output is switched: the picker still said Pop Rock while the
 * chip beside it said the preset the headset's profile happened to be saved
 * with (Ivan, 2026-09-24: "it says a different preset than selected so we
 * dont save presets on the output switch we replay current preset always").
 *
 * So a Preset layer that is playing survives the switch, and one that is not
 * is not brought back from a profile — a preset cleared by its chip's cross
 * stays cleared. Everything that is not a preset's curve is the output's as
 * it always was: somebody's own voicing belongs to the output they tuned it
 * on.
 *
 * `playing` absent means there is no live answer to prefer — the launch,
 * where the profile IS where the curve comes back from.
 */
const voicingForDevice = (
  saved: IVoicingSettings | undefined,
  playing: { voicing: IVoicingSettings | undefined } | undefined,
): IVoicingSettings | undefined => {
  if (!playing) {
    return saved;
  }
  const isPreset = (one: IVoicingSettings | undefined) =>
    dspVoicingPresetId(one) !== undefined;
  return isPreset(playing.voicing) || isPreset(saved) ? playing.voicing : saved;
};

export const getStateForAudioDevice = (
  settings: IDeviceProfileSettings,
  deviceId: string,
  presetDirForDevice: TPresetDirForDevice,
  /**
   * What the machine is playing right now, where the output is being switched
   * while the app runs. See `voicingForDevice`.
   */
  playing?: { voicing: IVoicingSettings | undefined },
): IState => {
  const defaultState = getDefaultState();
  const assignment = settings.assignments[deviceId];

  let preset: IPresetV2 | undefined;
  if (assignment) {
    try {
      preset = fetchPreset(
        assignment.presetName,
        presetDirForDevice(assignment.deviceId),
      );
    } catch {
      preset = undefined;
    }
  }

  return {
    ...defaultState,
    preAmp: preset?.preAmp ?? defaultState.preAmp,
    filters: preset?.filters ?? defaultState.filters,
    eqFormat: preset?.eqFormat,
    graphicEq: preset?.graphicEq,
    convolution: preset?.convolution,
    isFlat: preset?.isFlat,
    eqMode: getEqMode(preset ?? {}),
    curveEqMode: getCurveEqMode(preset ?? {}),
    eqBandQ: (preset ?? {}).eqBandQ,
    curveBandQ: (preset ?? {}).curveBandQ,
    curveSmoothing: (preset ?? {}).curveSmoothing,
    eqBandDesign: normalizeBandDesign(preset?.eqBandDesign),
    isEqDoubleOn: getEqMode(preset ?? {}) === 'double',
    // The profile's own tone, or none: a tone left from the output before
    // would follow somebody from the headphones to the speakers.
    tone: toTone(preset?.tone),
    voicing: voicingForDevice(preset?.voicing, playing),
    driver: preset?.driver,
    // Listed for the same reason as the rest, and missing for as long as it was
    // missing from the saved profile: an output that never asked for the
    // contour has to clear the one the previous output was using, or it follows
    // the user from the headphones to the speakers.
    smartEq: preset?.smartEq,
    headphone: preset?.headphone,
    eqImport: preset?.eqImport,
    customFx: undefined,
    headset: preset?.headset,
    headsetTarget: preset?.headsetTarget,
    headsetSource: preset?.headsetSource,
    // Listed like the rest, and for the same reason: a device whose profile
    // bypasses nothing has to clear whatever the previous one had switched off,
    // or a layer would arrive silent on an output that never switched it off.
    bypassed: preset?.bypassed,
    // Absent means automatic, which is what every profile written before the
    // flag existed was. Not `?? defaultState` — the default is the same value,
    // but saying so here keeps the rule in one place.
    isAutoPreAmpOn: preset?.isAutoPreAmpOn ?? true,
  };
};

export * from './audioDevices';
