/*
<AQUA: System-wide parametric audio equalizer interface>
Copyright (C) <2023> <AQUA Dev Team>
Copyright (C) <2026> <AQUA device-profile contributors>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 or later.
*/

import { execFile } from 'child_process';
import fs from 'fs';
import path from 'path';
import { createHash } from 'crypto';
import { promisify } from 'util';
import {
  IAudioDevice,
  IDeviceProfileAssignment,
  IDeviceProfileSettings,
  IPresetV2,
  IState,
  getDefaultState,
} from '../common/constants';
import {
  addFileToPath,
  FLUIDEQ_CONFIG_FILENAME,
  fetchPreset,
  stateToString,
} from './flush';
import { writeConvolutionWav } from './convolution';

export interface IActiveStateOverride {
  deviceId?: string;
  devicePattern: string;
  state: IState;
}

const isSafeConvolutionFileName = (fileName: string) =>
  fileName === path.basename(fileName) && !fileName.includes('..');

const execFileAsync = promisify(execFile);
const SETTINGS_FILENAME = 'device-profiles.json';

const getAudioDeviceScriptPath = () => {
  const scriptPath = path.join(
    process.resourcesPath,
    'assets',
    'windows-audio-devices.ps1',
  );
  const developmentScriptPath = path.join(
    __dirname,
    '../../assets/windows-audio-devices.ps1',
  );
  return fs.existsSync(scriptPath) ? scriptPath : developmentScriptPath;
};

export const getDefaultDeviceProfileSettings = (): IDeviceProfileSettings => ({
  version: 1,
  assignments: {},
});

export const loadDeviceProfileSettings = (
  userDataDir: string,
): IDeviceProfileSettings => {
  const settingsPath = path.join(userDataDir, SETTINGS_FILENAME);
  try {
    const input = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    if (input?.version !== 1 || typeof input.assignments !== 'object') {
      throw new Error('Unsupported device profile settings');
    }
    return input as IDeviceProfileSettings;
  } catch {
    return getDefaultDeviceProfileSettings();
  }
};

export const saveDeviceProfileSettings = (
  settings: IDeviceProfileSettings,
  userDataDir: string,
) => {
  fs.writeFileSync(
    path.join(userDataDir, SETTINGS_FILENAME),
    JSON.stringify(settings, null, 2),
    'utf8',
  );
};

export const assignDeviceProfile = (
  settings: IDeviceProfileSettings,
  assignment: IDeviceProfileAssignment,
) => {
  settings.assignments[assignment.deviceId] = assignment;
};

export const removeDeviceProfile = (
  settings: IDeviceProfileSettings,
  deviceId: string,
) => {
  delete settings.assignments[deviceId];
};

export const renameAssignedPreset = (
  settings: IDeviceProfileSettings,
  oldName: string,
  newName: string,
) => {
  Object.values(settings.assignments).forEach((assignment) => {
    if (assignment.presetName === oldName) {
      assignment.presetName = newName;
    }
  });
};

export const removeAssignmentsForPreset = (
  settings: IDeviceProfileSettings,
  presetName: string,
) => {
  Object.entries(settings.assignments).forEach(([deviceId, assignment]) => {
    if (assignment.presetName === presetName) {
      delete settings.assignments[deviceId];
    }
  });
};

const presetForDeviceToString = (
  assignment: IDeviceProfileAssignment,
  preset: IPresetV2,
  convolutionFileName?: string,
) => {
  const devicePattern = assignment.deviceGuid || assignment.deviceName;
  const presetState = {
    isEnabled: true,
    isAutoPreAmpOn: true,
    isGraphViewOn: false,
    isCaseSensitiveFs: false,
    ...preset,
  };

  return [
    `# ${assignment.deviceName} -> ${assignment.presetName}`,
    stateToString(presetState, convolutionFileName, devicePattern),
  ].join('\r\n');
};

const getConvolutionFileName = (deviceId: string) => {
  const digest = createHash('sha1').update(deviceId).digest('hex').slice(0, 12);
  return `fluideq-convolution-${digest}.wav`;
};

export const deviceProfilesToString = (
  settings: IDeviceProfileSettings,
  presetsDir: string,
  configDirPath?: string,
  activeOverride?: IActiveStateOverride,
  isEnabled = true,
) => {
  if (!isEnabled) {
    return [
      '# Generated by FluidEQ. Changes are overwritten automatically.',
      '# FluidEQ engine disabled; no Equalizer APO rules are active.',
    ].join('\r\n');
  }

  // Equalizer APO accumulates: every block whose `Device:` line matches the
  // output contributes its commands, and a later block does NOT reset an
  // earlier one. So if the device the user is listening on also has a preset
  // assigned, emitting both blocks stacks the preset's filters underneath the
  // live session instead of replacing them — pressing Clear EQ would leave the
  // preset fully audible. The session override wins, so its device drops out
  // of the assignment list entirely.
  const isOverriddenDevice = (assignment: IDeviceProfileAssignment) => {
    if (!activeOverride) {
      return false;
    }
    const pattern = assignment.deviceGuid || assignment.deviceName;
    return (
      (!!activeOverride.deviceId &&
        activeOverride.deviceId === assignment.deviceId) ||
      activeOverride.devicePattern === pattern
    );
  };

  const blocks = Object.values(settings.assignments)
    .filter((assignment) => !isOverriddenDevice(assignment))
    .map((assignment) => {
      try {
        const preset = fetchPreset(assignment.presetName, presetsDir);
        let convolutionFileName: string | undefined;
        if (configDirPath && preset.convolution) {
          convolutionFileName = getConvolutionFileName(assignment.deviceId);
          if (
            preset.convolution.fileName &&
            isSafeConvolutionFileName(preset.convolution.fileName)
          ) {
            convolutionFileName = preset.convolution.fileName;
          }
        }
        if (configDirPath && preset.convolution && convolutionFileName) {
          if (!preset.convolution.fileName) {
            writeConvolutionWav(
              addFileToPath(configDirPath, convolutionFileName),
              preset.convolution.filters,
            );
          }
        }
        return presetForDeviceToString(assignment, preset, convolutionFileName);
      } catch {
        return '';
      }
    })
    .filter(Boolean);

  let activeConvolutionFileName: string | undefined;
  if (activeOverride?.state.convolution) {
    if (
      activeOverride.state.convolution.fileName &&
      isSafeConvolutionFileName(activeOverride.state.convolution.fileName)
    ) {
      activeConvolutionFileName = activeOverride.state.convolution.fileName;
    } else if (configDirPath && activeOverride.deviceId) {
      activeConvolutionFileName = getConvolutionFileName(
        activeOverride.deviceId,
      );
      writeConvolutionWav(
        addFileToPath(configDirPath, activeConvolutionFileName),
        activeOverride.state.convolution.filters,
      );
    }
  }

  return [
    '# Generated by FluidEQ. Changes are overwritten automatically.',
    [
      '# Neutral fallback for every output without an attached profile.',
      'Device: all',
      'Channel: all',
    ].join('\r\n'),
    ...blocks,
    ...(activeOverride
      ? [
          [
            '# Active FluidEQ session override.',
            stateToString(
              activeOverride.state,
              activeConvolutionFileName,
              activeOverride.devicePattern,
            ),
          ].join('\r\n'),
        ]
      : []),
  ].join('\r\n\r\n');
};

/**
 * The full EQ state for a device, with every optional field present.
 *
 * Spreading a preset over the defaults is not enough, because callers apply the
 * result with Object.assign: a key the preset does not have is simply absent
 * from the object, so the assign leaves the PREVIOUS device's value in place.
 * That is how one device's convolution, voicing, driver correction or preamp
 * followed the user onto every other output — and, once edits started
 * auto-saving, got written into those devices' profiles for good.
 *
 * Every optional field is therefore listed explicitly, undefined included, so
 * assigning this over the live state clears what the new device does not have.
 */
export const getStateForAudioDevice = (
  settings: IDeviceProfileSettings,
  deviceId: string,
  presetsDir: string,
): IState => {
  const defaultState = getDefaultState();
  const assignment = settings.assignments[deviceId];

  let preset: IPresetV2 | undefined;
  if (assignment) {
    try {
      preset = fetchPreset(assignment.presetName, presetsDir);
    } catch {
      preset = undefined;
    }
  }

  return {
    ...defaultState,
    preAmp: preset?.preAmp ?? defaultState.preAmp,
    filters: preset?.filters ?? defaultState.filters,
    eqFormat: preset?.eqFormat,
    graphicEq: preset?.graphicEq,
    convolution: preset?.convolution,
    isFlat: preset?.isFlat,
    voicing: preset?.voicing,
    driver: preset?.driver,
  };
};

export const filterVisibleAudioDevices = (
  devices: IAudioDevice[],
): IAudioDevice[] => {
  const visibleByName = new Map<string, IAudioDevice>();

  devices
    .filter((device) => device.isActive && device.name.trim())
    .sort((left, right) => Number(right.isDefault) - Number(left.isDefault))
    .forEach((device) => {
      const normalizedName = device.name.trim().toLocaleLowerCase();
      if (!visibleByName.has(normalizedName)) {
        visibleByName.set(normalizedName, {
          ...device,
          name: device.name.trim(),
        });
      }
    });

  return [...visibleByName.values()].sort((left, right) => {
    return left.name.localeCompare(right.name);
  });
};

export const discoverAudioDevices = async (): Promise<IAudioDevice[]> => {
  if (process.platform !== 'win32') {
    return [
      {
        id: 'demo-speakers',
        name: 'Demo Speakers (Windows discovery runs on Windows)',
        guid: '{DEMO-SPEAKERS}',
        isDefault: true,
        isActive: true,
      },
      {
        id: 'demo-headphones',
        name: 'Demo Headphones',
        guid: '{DEMO-HEADPHONES}',
        isDefault: false,
        isActive: true,
      },
    ];
  }

  const { stdout } = await execFileAsync(
    'powershell.exe',
    [
      '-NoLogo',
      '-NoProfile',
      '-NonInteractive',
      '-ExecutionPolicy',
      'Bypass',
      '-File',
      getAudioDeviceScriptPath(),
    ],
    { windowsHide: true, timeout: 10000, maxBuffer: 1024 * 1024 },
  );
  const parsed = JSON.parse(stdout.trim() || '[]');
  return filterVisibleAudioDevices(
    (Array.isArray(parsed) ? parsed : [parsed]) as IAudioDevice[],
  );
};

export const setDefaultAudioDevice = async (deviceId: string) => {
  if (process.platform !== 'win32') {
    return;
  }

  const devices = await discoverAudioDevices();
  if (!devices.some((device) => device.id === deviceId)) {
    throw new Error('The selected audio output is no longer available.');
  }

  await execFileAsync(
    'powershell.exe',
    [
      '-NoLogo',
      '-NoProfile',
      '-NonInteractive',
      '-ExecutionPolicy',
      'Bypass',
      '-File',
      getAudioDeviceScriptPath(),
      '-SetDefaultDeviceId',
      deviceId,
    ],
    { windowsHide: true, timeout: 10000, maxBuffer: 1024 * 1024 },
  );
};

export const flushDeviceProfiles = (
  settings: IDeviceProfileSettings,
  presetsDir: string,
  configDirPath: string,
  activeOverride?: IActiveStateOverride,
  isEnabled = true,
) => {
  fs.writeFileSync(
    addFileToPath(configDirPath, FLUIDEQ_CONFIG_FILENAME),
    deviceProfilesToString(
      settings,
      presetsDir,
      configDirPath,
      activeOverride,
      isEnabled,
    ),
    'utf8',
  );
};
