/*
<AQUA: System-wide parametric audio equalizer interface>
Copyright (C) <2023> <AQUA Dev Team>
Copyright (C) <2026> <AQUA device-profile contributors>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 or later.
*/

import { execFile } from 'child_process';
import fs from 'fs';
import path from 'path';
import { promisify } from 'util';
import {
  IAudioDevice,
  IDeviceProfileAssignment,
  IDeviceProfileSettings,
  IPresetV2,
  IState,
  getDefaultState,
} from '../common/constants';
import {
  addFileToPath,
  AQUA_CONFIG_FILENAME,
  fetchPreset,
  stateToString,
} from './flush';

const execFileAsync = promisify(execFile);
const SETTINGS_FILENAME = 'device-profiles.json';

const getAudioDeviceScriptPath = () => {
  const scriptPath = path.join(
    process.resourcesPath,
    'assets',
    'windows-audio-devices.ps1'
  );
  const developmentScriptPath = path.join(
    __dirname,
    '../../assets/windows-audio-devices.ps1'
  );
  return fs.existsSync(scriptPath) ? scriptPath : developmentScriptPath;
};

export const getDefaultDeviceProfileSettings = (): IDeviceProfileSettings => ({
  version: 1,
  assignments: {},
});

export const loadDeviceProfileSettings = (
  userDataDir: string
): IDeviceProfileSettings => {
  const settingsPath = path.join(userDataDir, SETTINGS_FILENAME);
  try {
    const input = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    if (input?.version !== 1 || typeof input.assignments !== 'object') {
      throw new Error('Unsupported device profile settings');
    }
    return input as IDeviceProfileSettings;
  } catch {
    return getDefaultDeviceProfileSettings();
  }
};

export const saveDeviceProfileSettings = (
  settings: IDeviceProfileSettings,
  userDataDir: string
) => {
  fs.writeFileSync(
    path.join(userDataDir, SETTINGS_FILENAME),
    JSON.stringify(settings, null, 2),
    'utf8'
  );
};

export const assignDeviceProfile = (
  settings: IDeviceProfileSettings,
  assignment: IDeviceProfileAssignment
) => {
  settings.assignments[assignment.deviceId] = assignment;
};

export const removeDeviceProfile = (
  settings: IDeviceProfileSettings,
  deviceId: string
) => {
  delete settings.assignments[deviceId];
};

export const renameAssignedPreset = (
  settings: IDeviceProfileSettings,
  oldName: string,
  newName: string
) => {
  Object.values(settings.assignments).forEach((assignment) => {
    if (assignment.presetName === oldName) assignment.presetName = newName;
  });
};

export const removeAssignmentsForPreset = (
  settings: IDeviceProfileSettings,
  presetName: string
) => {
  Object.entries(settings.assignments).forEach(([deviceId, assignment]) => {
    if (assignment.presetName === presetName)
      delete settings.assignments[deviceId];
  });
};

const presetForDeviceToString = (
  assignment: IDeviceProfileAssignment,
  preset: IPresetV2
) => {
  const devicePattern = assignment.deviceGuid || assignment.deviceName;
  const presetState = {
    isEnabled: true,
    isAutoPreAmpOn: true,
    isGraphViewOn: false,
    isCaseSensitiveFs: false,
    ...preset,
  };

  return [
    `# ${assignment.deviceName} -> ${assignment.presetName}`,
    stateToString(presetState, devicePattern),
  ].join('\r\n');
};

export const deviceProfilesToString = (
  settings: IDeviceProfileSettings,
  presetsDir: string
) => {
  const blocks = Object.values(settings.assignments)
    .map((assignment) => {
      try {
        return presetForDeviceToString(
          assignment,
          fetchPreset(assignment.presetName, presetsDir)
        );
      } catch {
        return '';
      }
    })
    .filter(Boolean);

  return [
    '# Generated by FluidEQ. Changes are overwritten automatically.',
    [
      '# Neutral fallback for every output without an attached profile.',
      'Device: all',
      'Channel: all',
      'Preamp: 0 dB',
    ].join('\r\n'),
    ...blocks,
  ].join('\r\n\r\n');
};

export const getStateForAudioDevice = (
  settings: IDeviceProfileSettings,
  deviceId: string,
  presetsDir: string
): IState => {
  const defaultState = getDefaultState();
  const assignment = settings.assignments[deviceId];
  if (!assignment) return defaultState;

  try {
    return {
      ...defaultState,
      ...fetchPreset(assignment.presetName, presetsDir),
    };
  } catch {
    return defaultState;
  }
};

export const filterVisibleAudioDevices = (
  devices: IAudioDevice[]
): IAudioDevice[] => {
  const visibleByName = new Map<string, IAudioDevice>();

  devices
    .filter((device) => device.isActive && device.name.trim())
    .sort((left, right) => Number(right.isDefault) - Number(left.isDefault))
    .forEach((device) => {
      const normalizedName = device.name.trim().toLocaleLowerCase();
      if (!visibleByName.has(normalizedName)) {
        visibleByName.set(normalizedName, {
          ...device,
          name: device.name.trim(),
        });
      }
    });

  return [...visibleByName.values()].sort((left, right) => {
    return left.name.localeCompare(right.name);
  });
};

export const discoverAudioDevices = async (): Promise<IAudioDevice[]> => {
  if (process.platform !== 'win32') {
    return [
      {
        id: 'demo-speakers',
        name: 'Demo Speakers (Windows discovery runs on Windows)',
        guid: '{DEMO-SPEAKERS}',
        isDefault: true,
        isActive: true,
      },
      {
        id: 'demo-headphones',
        name: 'Demo Headphones',
        guid: '{DEMO-HEADPHONES}',
        isDefault: false,
        isActive: true,
      },
    ];
  }

  const { stdout } = await execFileAsync(
    'powershell.exe',
    [
      '-NoLogo',
      '-NoProfile',
      '-NonInteractive',
      '-ExecutionPolicy',
      'Bypass',
      '-File',
      getAudioDeviceScriptPath(),
    ],
    { windowsHide: true, timeout: 10000, maxBuffer: 1024 * 1024 }
  );
  const parsed = JSON.parse(stdout.trim() || '[]');
  return filterVisibleAudioDevices(
    (Array.isArray(parsed) ? parsed : [parsed]) as IAudioDevice[]
  );
};

export const setDefaultAudioDevice = async (deviceId: string) => {
  if (process.platform !== 'win32') return;

  const devices = await discoverAudioDevices();
  if (!devices.some((device) => device.id === deviceId)) {
    throw new Error('The selected audio output is no longer available.');
  }

  await execFileAsync(
    'powershell.exe',
    [
      '-NoLogo',
      '-NoProfile',
      '-NonInteractive',
      '-ExecutionPolicy',
      'Bypass',
      '-File',
      getAudioDeviceScriptPath(),
      '-SetDefaultDeviceId',
      deviceId,
    ],
    { windowsHide: true, timeout: 10000, maxBuffer: 1024 * 1024 }
  );
};

export const flushDeviceProfiles = (
  settings: IDeviceProfileSettings,
  presetsDir: string,
  configDirPath: string
) => {
  fs.writeFileSync(
    addFileToPath(configDirPath, AQUA_CONFIG_FILENAME),
    deviceProfilesToString(settings, presetsDir),
    'utf8'
  );
};
