/**
 * Public convolution sources and catalogue entries used by the renderer and
 * the Electron main process. AutoEq is the supported source because it has a
 * stable, machine-readable catalogue of correction WAVs that FluidEQ can
 * search, download, validate, and apply directly.
 */

export type ConvolutionSourceId = 'autoeq';

export interface IConvolutionSource {
  id: ConvolutionSourceId;
  name: string;
  description: string;
  website: string;
  downloadable: boolean;
}

export interface IConvolutionCatalogEntry {
  id: string;
  name: string;
  provider: string;
  sourceId: ConvolutionSourceId;
  sourceUrl: string;
  downloadUrl: string;
  format: 'wav';
  phase: 'minimum';
  sampleRate: 48000;
}

export const CONVOLUTION_SOURCES: IConvolutionSource[] = [
  {
    id: 'autoeq',
    name: 'AutoEq official',
    description: 'Headphone correction FIRs generated by AutoEq.',
    website: 'https://github.com/jaakkopasanen/AutoEq/tree/master/results',
    downloadable: true,
  },
];
