/**
 * Public convolution sources and catalogue entries used by the renderer and
 * the Electron main process. AutoEq is the only source with a stable,
 * machine-readable catalogue of headphone correction WAVs; the other links
 * are official research libraries that users can browse and import manually.
 */

export type ConvolutionSourceId = 'autoeq' | 'openair' | 'sadie' | 'aachen';

export interface IConvolutionSource {
  id: ConvolutionSourceId;
  name: string;
  description: string;
  website: string;
  downloadable: boolean;
}

export interface IConvolutionCatalogEntry {
  id: string;
  name: string;
  provider: string;
  sourceId: ConvolutionSourceId;
  sourceUrl: string;
  downloadUrl: string;
  format: 'wav';
  phase: 'minimum';
  sampleRate: 48000;
}

export const CONVOLUTION_SOURCES: IConvolutionSource[] = [
  {
    id: 'autoeq',
    name: 'AutoEq official',
    description: 'Headphone correction FIRs generated by AutoEq.',
    website: 'https://github.com/jaakkopasanen/AutoEq/tree/master/results',
    downloadable: true,
  },
  {
    id: 'openair',
    name: 'OpenAIR library',
    description: 'Academic room and acoustic impulse responses.',
    website: 'https://www.openairlib.net/',
    downloadable: false,
  },
  {
    id: 'sadie',
    name: 'SADIE II database',
    description: 'University of York binaural and headphone IR datasets.',
    website: 'https://www.york.ac.uk/sadie-project/database.html',
    downloadable: false,
  },
  {
    id: 'aachen',
    name: 'Aachen AIR database',
    description: 'RWTH Aachen room impulse response measurements.',
    website:
      'https://www.iks.rwth-aachen.de/en/research/tools-downloads/databases/aachen-impulse-response-database/',
    downloadable: false,
  },
];
