/*
<FluidEQ: System-wide parametric audio equalizer interface>
Copyright (C) <2026>  <Ivan Carmenates Garcia>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/**
 * Public convolution sources and catalogue entries used by the renderer and
 * the Electron main process. AutoEq is the supported source because it has a
 * stable, machine-readable catalogue of correction WAVs that FluidEQ can
 * search, download, validate, and apply directly.
 */

export type ConvolutionSourceId = 'autoeq';

export interface IConvolutionSource {
  id: ConvolutionSourceId;
  name: string;
  description: string;
  website: string;
  downloadable: boolean;
}

export interface IConvolutionCatalogEntry {
  id: string;
  name: string;
  provider: string;
  sourceId: ConvolutionSourceId;
  sourceUrl: string;
  downloadUrl: string;
  format: 'wav';
  phase: 'minimum';
  sampleRate: 48000;
}

export const CONVOLUTION_SOURCES: IConvolutionSource[] = [
  {
    id: 'autoeq',
    name: 'AutoEq official',
    description: 'Headphone correction FIRs generated by AutoEq.',
    website: 'https://github.com/jaakkopasanen/AutoEq/tree/master/results',
    downloadable: true,
  },
];
