/*
<FluidEQ: System-wide parametric audio equalizer interface>
Copyright (C) <2026>  <Ivan Carmenates Garcia>
SPDX-License-Identifier: GPL-3.0-or-later
*/

/** Freeze real encoder output for native decoding and TS fixture-drift checks. */
import { writeFileSync } from 'fs';
import path from 'path';
import { DSP_DEFAULTS } from '../../src/common/dsp/chain';
import { encodeChainSettings } from '../../src/common/dsp/chainWire';

const values = encodeChainSettings({
  ...DSP_DEFAULTS,
  gameMode: true,
  normalizer: { mode: 'loudness', truePeakDbtp: -2, targetLufs: -18 },
  room: {
    ...DSP_DEFAULTS.room,
    enabled: true,
    rendererVersion: 2,
    earlyReflectionDb: -12,
    ambienceMix: 0.35,
    ambienceDecayS: 1.2,
    ambienceDampingHz: 4500,
    preservePosition: true,
    compareOriginal: true,
    sourceAlreadySpatial: true,
  },
});
writeFileSync(
  path.resolve(process.cwd(), 'native/dsp-core/tests/room_contract_fixture.h'),
  `// Generated by .erb/scripts/generate-room-contract-fixture.ts; do not edit.\n#pragma once\ninline constexpr double kRoomContractFixture[] = {\n  ${values.join(', ')}\n};\n`,
);
